### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by SirWoofie** [McJty/RFToolsDimensions#1]
First time with this mod, third day modding Minecraft 1.8.9
RFToolsDim Teleportation Manager? Failed in my custom modpack, kinda confused and sad.

-I'm a bit lost.

// Ooh. Shiny.

Time: 1/25/16 8:35 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: Lmcjty/rftools/api/teleportation/ITeleportationManager;
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:543)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: Lmcjty/rftools/api/teleportation/ITeleportationManager;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredField(Unknown Source)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:44)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:540)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
	... 18 more
Caused by: java.lang.ClassNotFoundException: mcjty.rftools.api.teleportation.ITeleportationManager
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 689700208 bytes (657 MB) / 977272832 bytes (932 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722-universal.jar) 
	UC	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722-universal.jar) 
	UC	OpenComputers|Core{1.5.21.1} [OpenComputers (Core)] (minecraft.jar) 
	UC	cei{0.1} [Chunk Edge Indicator] (1.8.9-chunkedgeindicator-1.0.jar) 
	UC	adobeblocks{4.0.1.8} [Adobe Blocks] (AdobeBlocks-4.0.1.8.jar) 
	UC	adobeblocksvc{1.5} [Adobe Blocks 2 Version Checker] (AdobeBlocks-4.0.1.8.jar) 
	UC	animalbikes{1.8} [Animal Bikes] (AnimalBikes_1.8.8.jar) 
	UC	bagginses{2.1.4} [Bagginses] (Bagginses-1.8.9-2.1.4.jar) 
	UC	bedrockplus{0.2.0} [bedrockplus] (bedrockplus-0.2.0.jar) 
	UC	BedrockTools{1.2.1} [BedrockTools] (BedrockTools-1.2.1.jar) 
	UC	BetterTitleScreen{1.2} [Better Title Screen] (BetterTitleScreen-1.8.9-1.2.jar) 
	UC	Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
	UC	chiselsandbits{mc1.8.9-v1.8.6} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.6.jar) 
	UC	CLL{1.8.9-3.0.9} [Combustible Lemon Launcher] (CLL-1.8.9-3.0.9.jar) 
	UC	compasscoords{1.8.9-0.2.6} [Compass Co-ords] (CompassCoords-1.8.9-0.2.6.jar) 
	UC	ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
	UC	cosmeticarmorreworked{1.8.9-v1} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v1.jar) 
	UC	Ding{MC1.8.9} [Ding] (Ding-MC1.8.9.jar) 
	UC	eiramoticons{3.2.3} [EiraMoticons] (eiramoticons-mc1.8.9-3.2.3.jar) 
	UC	EnderZoo{1.8.9-1.1.0} [Ender Zoo] (EnderZoo-1.8.9-1.1.2.jar) 
	UC	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.2.jar) 
	UC	JEI{2.22.4.106} [Just Enough Items] (jei_1.8.9-2.22.4.106.jar) 
	UC	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UC	Thaumcraft{5.1.4} [Thaumcraft] (Thaumcraft-1.8.9-5.1.4.jar) 
	UC	OpenComputers{1.5.21.1} [OpenComputers] (OpenComputers-MC1.8.9-1.5.21.1.jar) 
	UC	FFS{1.8.9-1.4.4.68} [Fancy Fluid Storage] (Fancy Fluid Storage-1.8.9-1.4.4.68.jar) 
	UC	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UC	flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.5.jar) 
	UC	furnus{1.5} [Furnus] (Furnus-1.8.9-1.5.jar) 
	UC	JEIAddons{0.10.0.35} [Just Enough Items Addons] (JEIAddons_1.8.9-0.10.0.35.jar) 
	UC	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UC	launchgui{1.8.8-2.0.1-19} [LaunchGUI] (LaunchGui-1.8.8-2.0.1-19-client.jar) 
	UC	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UC	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UC	MoreFurnaces{1.5.0} [More Furnaces] (MoreFurnaces-1.5.0-MC1.8.9.jar) 
	UC	Morpheus{1.8.9-2.0.57} [Morpheus] (Morpheus-1.8.9-2.0.57.jar) 
	UC	MouseTweaks{2.6.0} [Mouse Tweaks] (MouseTweaks-2.6.0-mc1.8.9.jar) 
	UC	fodc{1.7.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.1.jar) 
	UC	packingtape{0.3} [Packing Tape] (Packing Tape-0.3.jar) 
	UC	portablecrafting{1.8.9-1.1} [Portable Crafting] (PortableCrafting-1.8.9-1.1.jar) 
	UC	ProjectE{1.8.9-PE1.1.3} [ProjectE] (ProjectE-1.8.9-PE1.1.3.jar) 
	UC	quickstart{1.0} [Quickstart] (quickstart-1.1.jar) 
	UC	RandomThings{3.5.8} [Random Things] (RandomThings-MC1.8.9-3.5.8.jar) 
	UC	rftools{4.20beta8} [RFTools] (rftools-1.8.9-4.20beta8.jar) 
	UE	rftoolsdim{4.20beta13} [RFTools Dimensions] (rftoolsdim-1.8.9-4.20beta13.jar) 
	UC	Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
	UC	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UC	simplefluidtanks{1.8.9-1.3.0.2} [Simple Fluid Tanks] (simplefluidtanks-1.8.9-1.3.0.2.jar) 
	UC	StorageDrawers{1.8.9-2.2.1} [Storage Drawers] (StorageDrawers-1.8.9-2.2.1.jar) 
	UC	thutcore{2.2.1} [ThutCore] (thutcore-2.2.1.jar) 
	UC	thuttech{2.2.5} [Thut's Tech] (thuttech-2.2.5.jar) 
	UC	trashslot{2.0.7} [TrashSlot] (trashslot-mc1.8.9-2.0.7.jar) 
	UC	VeinMiner{0.31.2_build.unknown} [Vein Miner] (VeinMiner-1.8.9_0.31.2.unknown.jar) 
	UC	VeinMinerModSupport{0.31.2_build.unknown} [Mod Support] (VeinMiner-1.8.9_0.31.2.unknown.jar) 
	UC	wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)
  
TransformerLoader (OpenComputers-MC1.8.9-1.5.21.1.jar)
  li.cil.oc.common.asm.ClassTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.8.9-3.5.8.jar)
  lumien.randomthings.asm.ClassTransformer
TrashSlot (trashslot-mc1.8.9-2.0.7.jar)
  net.blay09.mods.trashslot.coremod.GuiContainerClassTransformer
  net.blay09.mods.trashslot.coremod.MinecraftClassTransformer
  net.blay09.mods.trashslot.coremod.InventoryTweaksClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GT 420/PCIe/SSE2'
[20:35:34] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# K:\TravelMC MultiMC\instances\WolfCraft Travel 2.22\minecraft\crash-reports\crash-2016-01-25_20.35.33-client.txt
Process exited with code -1.

-Side note:   https://c418.bandcamp.com/album/148
 Also, do you mind explaining what some of these things mean, like the top area and transformers and stuff? Self-teaching has its disadvantages.

**Comment by McJty** [comment]
Wrong version of RFTools. Update rftools
