### ISSUE TITLE
concurrent exception while starting JEI

### ISSUE THREAD

**Issue by sanados** [McJty/RFToolsDimensions#12]
First start after creating modpack in Curse:

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-dev-49.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 04.05.16 16:01
Description: JEI failed to start:

com.google.common.util.concurrent.ExecutionError: java.lang.IllegalAccessError: tried to access method mcjty.rftoolsdim.dimensions.dimlets.KnownDimletConfiguration.initBiomeDimlet(Lnet/minecraft/world/biome/BiomeGenBase;)V from class mcjty.rftoolsdim.dimensions.dimlets.KnownDimletConfiguration$$dtt
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at mezz.jei.ItemFilter.<init>(ItemFilter.java:42)
	at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:173)
	at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:137)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.World.func_72838_d(World.java:1111)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:193)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2438)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2346)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:272)
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76)
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1041)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access method mcjty.rftoolsdim.dimensions.dimlets.KnownDimletConfiguration.initBiomeDimlet(Lnet/minecraft/world/biome/BiomeGenBase;)V from class mcjty.rftoolsdim.dimensions.dimlets.KnownDimletConfiguration$$dtt
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:965)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1387)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1739)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:442)
	at mcjty.rftoolsdim.dimensions.dimlets.KnownDimletConfiguration$$dtt.dt_131_initDimlets_33(Unknown Source)
	at mcjty.rftoolsdim.dimensions.dimlets.KnownDimletConfiguration.initDimlets(KnownDimletConfiguration.java:72)
	at mcjty.rftoolsdim.dimensions.dimlets.KnownDimletConfiguration.getSettings(KnownDimletConfiguration.java:44)
	at mcjty.rftoolsdim.items.KnownDimlet.func_77624_a(KnownDimlet.java:102)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:588)
	at mezz.jei.util.ItemStackElement.<init>(ItemStackElement.java:76)
	at mezz.jei.util.ItemStackElement.create(ItemStackElement.java:45)
	at mezz.jei.ItemFilter.createBaseList(ItemFilter.java:88)
	at mezz.jei.ItemFilter.access$100(ItemFilter.java:29)
	at mezz.jei.ItemFilter$ItemFilterCacheLoader.load(ItemFilter.java:123)
	at mezz.jei.ItemFilter$ItemFilterCacheLoader.load(ItemFilter.java:113)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 30 more

**Comment by McJty** [comment]
I need more information. What version of MC? What version of all the mods?

**Comment by sanados** [comment]
Sorry that i forgot to add them.

mc 1.9
forge: 12.16.1.1887


JEI: 1.9.-3.3.3.197
rftools: 1.9.0-4.46
rftools dim: 1.9.0-423beta

**Comment by sanados** [comment]
Java: 1.8.0_77

**Comment by McJty** [comment]
Please upgraded to 1.10.2. I don't support 1.9.0 anymore
