### ISSUE TITLE
[1.12] Machines from RFTools Dimensions not working

### ISSUE THREAD

**Issue by LiEyWe** [McJty/RFToolsDimensions#123]
When I place Machines, the white stripes on the front side disappear immediately and I can't open the GUI. I use the latest version and have the following mods installed:
McJtyLib
RFTools
RFTools Dimensions

**Comment by McJty** [comment]
What?? That's extremely weird. Can you show a screenshot? Also logs

**Comment by LiEyWe** [comment]
http://imgur.com/a/kl2xi that pic shows the dimension builder not turning on.
Here are the logs:
https://pastebin.com/y4tyfizi
Unfortunately, I can't upload the fml logs, cause they exceed the upload limit on pastebin.

**Comment by astradamus** [comment]
Precisely the same issue here. With Dimension Builders, that is.


**_EDIT: After staring at this for a few minutes, I found the apparent original issue:
Caused by: java.lang.NoSuchMethodError: mcjty.rftoolsdim.blocks.builder.DimensionBuilderTileEntity.getEnergyStored(Lnet/minecraft/util/EnumFacing;)I
at mcjty.rftoolsdim.blocks.builder.GuiDimensionBuilder.(GuiDimensionBuilder.java:37) ~_**


I was able to narrow it down to the exact exception. This shows up in latest.log each time you right-click the builder:

[04:51:46] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bhz.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bhz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at mcjty.lib.container.GenericBlock.createClientGui(GenericBlock.java:651) ~[GenericBlock.class:?]
	at mcjty.rftoolsdim.gui.GuiProxy.getClientGuiElement(GuiProxy.java:64) ~[GuiProxy.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:277) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2544) ~[aeb.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler$$Lambda$468/1927336641.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
	at mcjty.lib.container.GenericBlock.createClientGui(GenericBlock.java:647) ~[GenericBlock.class:?]
	at mcjty.rftoolsdim.gui.GuiProxy.getClientGuiElement(GuiProxy.java:64) ~[GuiProxy.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:277) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2544) ~[aeb.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler$$Lambda$468/1927336641.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
Caused by: java.lang.NoSuchMethodError: mcjty.rftoolsdim.blocks.builder.DimensionBuilderTileEntity.getEnergyStored(Lnet/minecraft/util/EnumFacing;)I
	at mcjty.rftoolsdim.blocks.builder.GuiDimensionBuilder.<init>(GuiDimensionBuilder.java:37) ~[GuiDimensionBuilder.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
	at mcjty.lib.container.GenericBlock.createClientGui(GenericBlock.java:647) ~[GenericBlock.class:?]
	at mcjty.rftoolsdim.gui.GuiProxy.getClientGuiElement(GuiProxy.java:64) ~[GuiProxy.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:277) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2544) ~[aeb.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler$$Lambda$468/1927336641.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[04:51:47]

**Comment by astradamus** [comment]
This is all that comes in in the FML log.
[04:51:46] [main/ERROR] [mcjty.lib.varia.Logging/]: Severe exception during creation of gui!

**Comment by McJty** [comment]
You can work around this by adding redstoneflux mod from cofh until I am back from vacation and can fix this

**Comment by astradamus** [comment]
That worked. Thanks for the workaround! Let me know if you need any more crash data when you get around to fixing it and I can probably reproduce it again if you're somehow unable.

**Comment by McJty** [comment]
Fixed for real next release
