### ISSUE TITLE
The game crashes when I enter the dimlet workbench

### ISSUE THREAD

**Issue by nivi159** [McJty/RFToolsDimensions#135]
I don't know what happens. Help plz

**Comment by nivi159** [comment]
Oh and here is my crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  DLFMLCorePlugin (DynamicLights-1.12.1.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 8/24/17 10:37 AM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:114)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:226)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:114)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:226)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['WarriorKing06'/162076, l='New World', x=45.76, y=81.00, z=340.98]]
	Chunk stats: ServerChunkCache: 611 Drop: 0
	Level seed: 5437035098629495547
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (220,64,252), Chunk: (at 12,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6677 game time, 16732 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 34883 (now: false), thunder time: 85123 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 180718672 bytes (172 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.41 Powered by Forge 14.22.0.2460 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State                    | ID                          | Version      | Source                         | Signature                                |
	|:------------------------ |:--------------------------- |:------------ |:------------------------------ |:---------------------------------------- |
	| UCHIJAAAAAAAAAAAAAAAAAAA | minecraft                   | 1.12.1       | minecraft.jar                  | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | mcp                         | 9.19         | minecraft.jar                  | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | FML                         | 8.0.99.99    | forge-1.12.1-14.22.0.2460.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | forge                       | 14.22.0.2460 | forge-1.12.1-14.22.0.2460.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | mercurius_updater           | 1.0          | MercuriusUpdater-1.12.1.jar    | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | blockarmor                  | 2.4.6        | BlockArmor-1.12-2.4.6.jar      | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | dynamiclights               | 1.4.6        | DynamicLights-1.12.1.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | dynamiclights_onfire        | 1.0.7        | DynamicLights-1.12.1.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | dynamiclights_creepers      | 1.0.6        | DynamicLights-1.12.1.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | dynamiclights_dropitems     | 1.1.0        | DynamicLights-1.12.1.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | dynamiclights_entityclasses | 1.0.1        | DynamicLights-1.12.1.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | dynamiclights_mobequipment  | 1.1.0        | DynamicLights-1.12.1.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | dynamiclights_flamearrows   | 1.0.1        | DynamicLights-1.12.1.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | dynamiclights_floodlights   | 1.0.3        | DynamicLights-1.12.1.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | dynamiclights_otherplayers  | 1.0.9        | DynamicLights-1.12.1.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | dynamiclights_theplayer     | 1.1.3        | DynamicLights-1.12.1.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | inventorypets               | 1.4.9.8      | inventorypets-1.12-1.4.9.8.jar | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | levelup2                    | ${version}   | Level Up! 2-1.1.5-1.12.jar     | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | ropebridge                  | 2.0.5        | ropebridge-1.12-2.0.7.jar      | None                                     |

	Loaded coremods (and transformers): 
DLFMLCorePlugin (DynamicLights-1.12.1.jar)
  atomicstryker.dynamiclights.common.DLTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['WarriorKing06'/162076, l='New World', x=45.76, y=81.00, z=340.98]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

Sorry that's so long!

**Comment by McJty** [comment]
That crash is not related to the dimlet workbench. Can you try again and give me the full log?
