### ISSUE TITLE
Upside down dimension crashes

### ISSUE THREAD

**Issue by McJty** [McJty/RFToolsDimensions#177]
Trying to create an upside down dimension gives this:

```
[06:40:23] [Server thread/INFO]: id = 3 for , descriptor = @XCheater
[06:40:23] [Server thread/INFO]:     Base seed: 8830016153103610036
[06:40:23] [Server thread/INFO]:     World version: 2
[06:40:23] [Server thread/INFO]:     Terrain: TERRAIN_INVERTIGO
[06:40:23] [Server thread/INFO]:         Base block: Stone
[06:40:23] [Server thread/INFO]:         Base fluid: Water
[06:40:23] [Server thread/INFO]:     Biome controller: CONTROLLER_CHECKERBOARD
[06:40:23] [Server thread/INFO]:     Biome: Plains
[06:40:23] [Server thread/INFO]:     Sun brightness: 1.0
[06:40:23] [Server thread/INFO]:     Star brightness: 1.0
[06:40:23] [Server thread/INFO]:     Sky color: 1.0, 1.0, 1.0
[06:40:23] [Server thread/INFO]:     Fog color: 1.0, 1.0, 1.0
[06:40:23] [Server thread/INFO]:     Cloud color: 1.0, 1.0, 1.0
[06:40:23] [Server thread/INFO]:     Sky body: BODY_SUN
[06:40:23] [Server thread/INFO]:     Sky body: BODY_SUN
[06:40:23] [Server thread/INFO]:     CHEATER!
[06:40:23] [Server thread/INFO]: Sync dimension info to clients!
[06:40:23] [main/INFO]: Client side, already registered dimension: 3
[06:40:23] [Server thread/INFO]: Loading dimension 3 (New World) (net.minecraft.server.integrated.IntegratedServer@5e8de03d)
[06:40:23] [main/INFO]: Received dimension information from server
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator:getSettings:177]: dimensionInformation = mcjty.rftoolsdim.dimensions.DimensionInformation@2419c53a
[06:40:23] [Server thread/ERROR]: Something went wrong during creation of the dimension!
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: java.lang.NullPointerException
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at mcjty.rftoolsdim.dimensions.world.UpsidedownWorld.createChunkProvider(UpsidedownWorld.java:142)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:124)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at mcjty.rftoolsdim.dimensions.world.UpsidedownWorld.<init>(UpsidedownWorld.java:27)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.populate(GenericChunkGenerator.java:451)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at mcjty.rftoolsdim.dimensions.RfToolsDimensionManager.touchSpawnChunk(RfToolsDimensionManager.java:433)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at mcjty.rftoolsdim.dimensions.RfToolsDimensionManager.createNewDimension(RfToolsDimensionManager.java:421)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at mcjty.rftoolsdim.blocks.builder.DimensionBuilderTileEntity.createDimensionTick(DimensionBuilderTileEntity.java:211)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at mcjty.rftoolsdim.blocks.builder.DimensionBuilderTileEntity.checkStateServer(DimensionBuilderTileEntity.java:114)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at mcjty.rftoolsdim.blocks.builder.DimensionBuilderTileEntity.update(DimensionBuilderTileEntity.java:96)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at net.minecraft.world.World.updateEntities(World.java:2004)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:642)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:840)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
[06:40:23] [Server thread/INFO]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:touchSpawnChunk:436]: 	at java.lang.Thread.run(Thread.java:745)
[06:40:23] [Server thread/INFO]: Unloading dimension 3
[06:40:50] [main/INFO]: Loaded 2 advancements
```

**Comment by McJty** [comment]
I think this worked fine before so something might have changed here

**Comment by josephcsible** [comment]
This is [the](https://www.javaspecialists.eu/archive/Issue210.html) [exact](http://www.javapractices.com/topic/TopicAction.do?Id=215) [reason](https://stackoverflow.com/questions/3404301/whats-wrong-with-overridable-method-calls-in-constructors) why you're not supposed to call overridable methods from constructors, Mojang. :unamused:

**Comment by josephcsible** [comment]
The reason that this works with the anonymous subclass is that captured variables "cheat". Basically, instead of this:
```java
    public UpsidedownWorld(WorldServer worldServer) {
        super(worldServer.getMinecraftServer(), worldServer.getSaveHandler(), worldServer.getWorldInfo(), worldServer.provider.getDimension(), worldServer.profiler);
        this.worldObj = worldServer;
        this.ww = worldServer;
    }
```
They do this:
```java
    public UpsidedownWorld(WorldServer worldServer) {
        this.ww = worldServer;
        super(worldServer.getMinecraftServer(), worldServer.getSaveHandler(), worldServer.getWorldInfo(), worldServer.provider.getDimension(), worldServer.profiler);
        this.worldObj = worldServer;
    }
```
The latter is not actually valid Java; the only way you'll get code that acts like that is with a trick like the anonymous subclass.
