### ISSUE TITLE
Can't start DW20 with latest version

### ISSUE THREAD

**Issue by josephcsible** [McJty/RFToolsDimensions#179]
```
Encountered an unexpected exception
java.lang.ExceptionInInitializerError
	at mcjty.rftoolsdim.dimensions.world.GenericWorldGenerator.generate(GenericWorldGenerator.java:59)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1016)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:996)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: randomSeed
	at mcjty.rftoolsdim.dimensions.RfToolsDimensionManager.<clinit>(RfToolsDimensionManager.java:399)
	... 10 more
Caused by: java.lang.NoSuchFieldException: randomSeed
	at java.lang.Class.getDeclaredField(Class.java:2062)
	at mcjty.rftoolsdim.dimensions.RfToolsDimensionManager.<clinit>(RfToolsDimensionManager.java:397)
	... 10 more
```

**Comment by josephcsible** [comment]
I accidentally tried a build with some leftover reflection that wasn't meant for release (and isn't in the real release.)
