### ISSUE TITLE
Crash on joining an unpowered Dimension with Phased Field Generator

### ISSUE THREAD

**Issue by darkman1984** [McJty/RFToolsDimensions#188]
Hi!

When i try to join an unpowered Dimension with the Phased Field Generator the server will crash with the following Crashlog.

Description: Exception in server tick loop

```
java.lang.ClassCastException: appeng.spatial.StorageWorldProvider cannot be cast to mcjty.rftoolsdim.dimensions.world.GenericWorldProvider
	at mcjty.rftoolsdim.dimensions.RfToolsDimensionManager.freezeDimension(RfToolsDimensionManager.java:146)
	at mcjty.rftoolsdim.dimensions.DimensionStorage.setEnergyLevel(DimensionStorage.java:64)
	at mcjty.rftoolsdim.dimensions.DimensionTickEvent.handlePower(DimensionTickEvent.java:109)
	at mcjty.rftoolsdim.dimensions.DimensionTickEvent.serverTick(DimensionTickEvent.java:74)
	at mcjty.rftoolsdim.dimensions.DimensionTickEvent.onWorldTick(DimensionTickEvent.java:54)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1037_DimensionTickEvent_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

I really don't know why the Applied Energistics Storage World Provider is in there?

- RFTools Dimension Version: 5.50
- Game Version: 1.12.2
- Forge: 14.23.1.2590
- Applied Energistics Version: RV5 Stable 5

Greetings
DaRkMaN

**Comment by josephcsible** [comment]
Looks like AE2's spatial storage was using the same dimension ID as one of our dimensions were using. Not sure if it's our fault or theirs yet. Can you see if you can reproduce this consistently in a fresh save, and if so, what's the exact order of steps that causes it?

**Comment by darkman1984** [comment]
I can try it but cannot promise that i can reproduce the same error.
But i think you're right, cause the output of /rftdim list says:
[Server thread/INFO]:     Loaded: id:2, Storage Cell
[Server thread/INFO]:     RfTools: id:2, Draconic Ore (power 0) (owner DaRkMaN1984)

I think the fault depends on applied energistics that they don't have a check if a dimension-id is available or not.

There are no special steps i've done, only jump back from refined storage to the actual RV5 Stable 5 Applied Energistics Version - BUT - i think the dimension von RFTools would be created where Applied Energistics was not installed.
