### ISSUE TITLE
Crash when trying to inject matter receiver

### ISSUE THREAD

**Issue by josephcsible** [McJty/RFToolsDimensions#195]
```
java.lang.NullPointerException: Ticking block entity
        at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.update(DimensionEditorTileEntity.java:107)
        at net.minecraft.world.World.updateEntities(World.java:2004)
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:642)
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:840)
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:414)
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
        at java.lang.Thread.run(Thread.java:748)
```

Somehow "id" got set to a dimension we don't recognize.

**Comment by xxMattewxx** [comment]
```
`[13:14:33] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) ~[bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at mcjty.rftoolsdim.dimensions.world.terrain.NormalTerrainGenerator.replaceBlocksForBiome(NormalTerrainGenerator.java:322) ~[NormalTerrainGenerator.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.func_185932_a(GenericChunkGenerator.java:289) ~[GenericChunkGenerator.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140) ~[lr.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) ~[aid.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) ~[aid.class:?]
	at net.minecraft.world.World.func_175672_r(World.java:1612) ~[aid.class:?]
	at mcjty.rftoolsdim.dimensions.world.WorldGenerationTools.findSuitableEmptySpot(WorldGenerationTools.java:12) ~[WorldGenerationTools.class:?]
	at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.findGoodReceiverLocation(DimensionEditorTileEntity.java:222) ~[DimensionEditorTileEntity.class:?]
	at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.func_73660_a(DimensionEditorTileEntity.java:135) ~[DimensionEditorTileEntity.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more`

`java.lang.NullPointerException: Exception generating new chunk
	at mcjty.rftoolsdim.dimensions.world.terrain.NormalTerrainGenerator.replaceBlocksForBiome(NormalTerrainGenerator.java:322)
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.func_185932_a(GenericChunkGenerator.java:289)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_175672_r(World.java:1612)
	at mcjty.rftoolsdim.dimensions.world.WorldGenerationTools.findSuitableEmptySpot(WorldGenerationTools.java:12)
	at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.findGoodReceiverLocation(DimensionEditorTileEntity.java:222)
	at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.func_73660_a(DimensionEditorTileEntity.java:135)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)`
```

Confirmed it is happening on version 4.45 of RFTools Dimensions, RFTools 5.62, forge 12.18.3.2477.
The crash log is different from the OP, but the issue is the same. Crashes when sending a matter receiver.

**Comment by josephcsible** [comment]
It's only a coincidence that the matter receiver is what triggered both of these. Your crash is a completely different issue; please open a separate ticket for it.

**Comment by xxMattewxx** [comment]
Receiver gets sent actually. Loading the world after the crash, you can see the receiver is working fine.

**Comment by Yarillo4** [comment]
I confirm it still happened on RFTools Dim 1.12 - 5.64 :+1: . I tried injecting a matter receiver in the dimension because I couldn't teleport to it.

* McJtylib 3.1.1 (latest)
* RFTools Dim 5.64 (latest)
* RFTools 7.61 (latest)
* Forge 14.23.5.2815 (latest)
* RedstoneFlux 1.12-2.1.0.6-universal (latest)

Now I've got a lot of other mods installed, including core mods, and I use optifine, so, it's not the best. But have my crash log anyway.

[CRASH LOGS](https://pastebin.com/2sJfM3xh)

```
java.lang.NullPointerException: Exception generating new chunk
	at mcjty.rftoolsdim.dimensions.world.terrain.NormalTerrainGenerator.replaceBlocksForBiome(NormalTerrainGenerator.java:321)
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.func_185932_a(GenericChunkGenerator.java:305)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_175672_r(World.java:1619)
	at mcjty.rftoolsdim.dimensions.world.WorldGenerationTools.findSuitableEmptySpot(WorldGenerationTools.java:24)
	at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.findGoodReceiverLocation(DimensionEditorTileEntity.java:236)
	at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.func_73660_a(DimensionEditorTileEntity.java:146)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```
