### ISSUE TITLE
Entering an unpowered dimension causes crash if player is in creative mode.

### ISSUE THREAD

**Issue by xxMattewxx** [McJty/RFToolsDimensions#202]
Issue description: Client crashes when entering an unpowered dimension (powered dimensions work fine. Problem seems to only happen if in creative mode.

Steps to reproduce: Create a dimension, teleport to it in creative mode. After few seconds the client crash.

Versions:
* Minecraft: 1.10.2
* Forge: 12.18.3.2477
* CompatLayer (only if on Minecraft 1.10 or 1.11): Not installed (I think?)
* McJtyLib: 2.2.0
* RFTools: 5.62
* RFTools Dimensions: 4.45

Possibly incompatible mods: OptiFine

Relevant logs, if any: When the issue happened no logs were created apparently (As I can see other logs but no logs from today)
However I remember in the console it showing something about an exception ticking world. Perhaps the dimension being unpowered, RFT dimensions tried stopping its ticks? I don't know.

**Comment by josephcsible** [comment]
If there's no logs, there's nothing we can do. Try to reproduce it.

**Comment by xxMattewxx** [comment]
[19:29:56] [Client thread/INFO] [STDERR]: [net.minecraftforge.common.DimensionManager:initDimension:223]: Cannot Hotload Dim: Could not get provider type for dimension 2, does not exist
[19:30:01] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) ~[bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.func_72907_a(World.java:3135) ~[aid.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.func_177458_a(GenericChunkGenerator.java:514) ~[GenericChunkGenerator.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_177458_a(ChunkProviderServer.java:298) ~[lr.class:?]
	at net.minecraft.world.WorldServer.func_175732_a(WorldServer.java:246) ~[ls.class:?]
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:134) ~[aik.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) ~[MinecraftServer.class:?]
	... 4 more
[19:30:01] [Server thread/ERROR]: This crash report has been saved to: C:\Users\BROTHERS\AppData\Roaming\.minecraft\crash-reports\crash-2018-02-24_19.30.01-server.txt
[19:30:01] [Server thread/INFO]: Stopping server
[19:30:01] [Server thread/INFO]: Saving players
[19:30:01] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  HammerCoreCore (HammerCore-1.10.2-1.9.4.3.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  IC2core (industrialcraft-2-2.6.252-ex110.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 24/02/18 19:30
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.World.func_72907_a(World.java:3135)
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.func_177458_a(GenericChunkGenerator.java:514)
	at net.minecraft.world.gen.ChunkProviderServer.func_177458_a(ChunkProviderServer.java:298)
	at net.minecraft.world.WorldServer.func_175732_a(WorldServer.java:246)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:134)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.func_72907_a(World.java:3135)
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.func_177458_a(GenericChunkGenerator.java:514)
	at net.minecraft.world.gen.ChunkProviderServer.func_177458_a(ChunkProviderServer.java:298)
	at net.minecraft.world.WorldServer.func_175732_a(WorldServer.java:246)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:134)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198)

**Comment by xxMattewxx** [comment]
[crash-2018-02-24_19.30.01-server.txt](https://github.com/McJty/RFToolsDimensions/files/1755380/crash-2018-02-24_19.30.01-server.txt)
