### ISSUE TITLE
Crash when loading single player world after playing on server

### ISSUE THREAD

**Issue by Frefreak** [McJty/RFToolsDimensions#205]
Issue description:

I'm not that sure it's rftoolsdim's fault, sorry if it's not :)
It's a custom pack made to play with my friends. From time to time we add mods to it and it seems to work fine (a Garden of Glass map). But recently we notice if one enters the server and quit, then try to load a single player map (or create a new one), the game stuck on "loading world", and the log shows there's a crash, the bottom of call stack lies in rftoolsdim. The 3 rftools mods have been added for some time and only recently we noticed this issue so I'm not sure if this pack has this issue from the day we added it. The mod list is below (most recent added mods are bibliocraft and chisel & bits).

Steps to reproduce: 

open game, load a single player world, works fine. Then play on a forge server with same mods (except a server side mod), works fine. Then try to load a single player world, game stuck at "loading world", and a crash log saved.

Versions:
* Minecraft: 1.12
* Forge: 2601 (tried 2611, same)
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-2.6.4-SNAPSHOT
* RFTools: 1.12-7.29
* RFTools Dimensions: 1.12-5.52

Has optifine client side, tried disable it, problem still persist.

Possibly incompatible mods: 
Recently we added bibliocraft and chisel &  bits.

[modlist](http://lpaste.net/363119)
[crash log](http://lpaste.net/363120)

**Comment by josephcsible** [comment]
https://github.com/McJty/RFToolsDimensions/blob/dac47f72eb98de77303d903b273a5f78ed73c58a/src/main/java/mcjty/rftoolsdim/dimensions/world/GenericChunkGenerator.java#L211-L215

It looks like for some reason we don't have dimension information for one of our dimensions.

**Comment by Morpheus1101** [comment]
Glad this has all ready been reported.

**Comment by juliand665** [comment]
Still happening with 1.12-5.60 😞

**Comment by Towhead1212** [comment]
im playing with the direwolf20 pack and this is happening

**Comment by shinji257** [comment]
I'm currently on a custom pack and getting this issue.

Crash log after trying to create or join a single player world with no dimensions but having joined multiplayer prior (to reproduce the issue).  Reloading the entire pack resolves the issue until I play multiplayer again.

https://paste.dimdev.org/riropixiwi.mccrash

It appears that dimension information from a multiplayer server connection isn't being properly cleaned up.

Looking at the server connection I see this.
`[11:42:59] [Netty Client IO #1/INFO] [mcjtylib_ng]: DimensionSyncPacket: Registering: 4 5 7 8 10 `

Later when I try to join single player though (without a pack reload) I see this
```
[11:44:27] [Server thread/ERROR] [mcjtylib_ng]: Catching
java.lang.RuntimeException: Dimension information for dimension 4 is missing!
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.getDimensionInformation(GenericWorldProvider.java:91) [GenericWorldProvider.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.createBiomeProviderInternal(GenericWorldProvider.java:229) [GenericWorldProvider.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.init(GenericWorldProvider.java:220) [GenericWorldProvider.class:?]
	at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:40) [aym.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116) [oo.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18) [ok.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:106) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:213) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[11:44:27] [Server thread/ERROR] [mcjtylib_ng]: Catching
java.lang.RuntimeException: Dimension information for dimension 4 is missing!
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.getDimensionInformation(GenericWorldProvider.java:91) [GenericWorldProvider.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.generateLightBrightnessTable(GenericWorldProvider.java:196) [GenericWorldProvider.class:?]
	at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:41) [aym.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116) [oo.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18) [ok.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:106) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:213) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[11:44:27] [Server thread/INFO] [mcjtylib_ng]: Error: setSeed() called with null diminfo. Error ignored!
[11:44:27] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.<init>(GenericChunkGenerator.java:215) ~[GenericChunkGenerator.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.createChunkGenerator(GenericWorldProvider.java:356) ~[GenericWorldProvider.class:?]
	at net.minecraft.world.WorldServer.createChunkProvider(WorldServer.java:848) ~[oo.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:118) ~[oo.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18) ~[ok.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:106) ~[chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:213) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

This suggests that it is attempting to re-use dimensions registered from a multiplayer connection on a singleplayer world.  Even one being freshly created (this specific crash was from a new world creation).

If you need the full log from the session let me know.  I have not uploaded it yet since it is about 3MB but I set it aside so I can get anything from it or even post it in full somewhere.

**Comment by Morpheus1101** [comment]
wow, i even commented on this long ago.. Adding my crash log here for future reference https://pastebin.com/XMvtBctT

**Comment by Sandrituky** [comment]
I'm playing 1.12.2 and still happening...

**Comment by McJty** [comment]
I no longer work on 1.12 so this is not going to get fixed. Best to exit Minecraft after switching from MP to SP or the other way around. Sorry
