### ISSUE TITLE
Possible issue with EnderIO fluid conduits and being in a custom dimension

### ISSUE THREAD

**Issue by Henry-R** [McJty/RFToolsDimensions#210]
Issue description: 
Client crashing shortly after entering custom dimension.

Steps to reproduce: 
I created a dimension for mining and setup a builder quarry with a codechicken ender chest and a power cell for wireless power. After 30-ish seconds every time I enter the dimension the client crashes with a error message saying something about ender io fluid conduits. The builder works when I am there and I can load back into the world and exit the dimension before the client crashes again.

Versions:
* Minecraft:                     1.12.2
* Forge:                          14.23.3.2669
* McJtyLib:                      1.12-2.6.7
* RFTools:                        1.12-7.33
* RFTools Dimensions:      1.12-5.53

Possibly incompatible mods: 
Ender IO

Client Crash Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Wizardry Plugin (wizardry-0.8.5.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 4/8/18 10:35 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at vazkii.botania.client.model.GunModel.<init>(GunModel.java:42)
	at vazkii.botania.client.core.handler.MiscellaneousIcons.onModelBake(MiscellaneousIcons.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_324_MiscellaneousIcons_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at vazkii.botania.client.model.GunModel.<init>(GunModel.java:42)
	at vazkii.botania.client.core.handler.MiscellaneousIcons.onModelBake(MiscellaneousIcons.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_324_MiscellaneousIcons_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 56552192 bytes (53 MB) / 564428800 bytes (538 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2654 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                          | Signature                                |
	|:----- |:------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                 | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                 | 8.0.99.99                | forge-1.12.2-14.23.2.2654-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.2.2654             | forge-1.12.2-14.23.2.2654-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | astralsorcery       | 1.8.5                    | astralsorcery-1.12.2-1.8.5.jar                  | None                                     |
	| UCH   | quark               | r1.4-123                 | Quark-r1.4-123.jar                              | None                                     |
	| UCH   | autoreglib          | 1.3-16                   | AutoRegLib-1.3-16.jar                           | None                                     |
	| UCH   | baubles             | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCH   | betterbuilderswands | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | bibliocraft         | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCH   | botania             | r1.10-353                | Botania+r1.10-353.jar                           | None                                     |
	| UCH   | chisel              | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCH   | chiselsandbits      | 14.16                    | chiselsandbits-14.16.jar                        | None                                     |
	| UCH   | codechickenlib      | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | cucumber            | 1.1.0                    | cucumber-1.12-1.1.0.jar                         | None                                     |
	| UCH   | jei                 | 4.8.5.159                | jei_1.12.2-4.8.5.159.jar                        | None                                     |
	| UCH   | cyclicmagic         | 1.14.7                   | Cyclic-1.12.2-1.14.7.jar                        | None                                     |
	| UCH   | enderstorage        | 2.4.0.122                | EnderStorage-1.12-2.4.0.122-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | extraalchemy        | 0.3.8.2-release          | extraalchemy-0.3.8.2-release.jar                | None                                     |
	| UCH   | forgelin            | 1.6.0                    | Forgelin-1.6.0.jar                              | None                                     |
	| UCH   | llibrary            | 1.7.9                    | llibrary-1.7.9-1.12.2.jar                       | None                                     |
	| UCH   | iceandfire          | 1.4.0                    | iceandfire-1.4.0-1.12.2.jar                     | None                                     |
	| UCH   | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | wizardry            | 0.8.5                    | wizardry-0.8.5.jar                              | None                                     |
	| UCH   | librarianlib        | 9.4                      | librarianlib-1.12.2-4.9.jar                     | None                                     |
	| UCH   | mantle              | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCH   | mousetweaks         | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCH   | mysticalagriculture | 1.6.9                    | mysticalagriculture-1.12-1.6.9.jar              | None                                     |
	| UCH   | natura              | 1.12.2-4.3.2.42          | natura-1.12.2-4.3.2.42.jar                      | None                                     |
	| UCH   | xreliquary          | 1.12.2-1.3.4.757         | Reliquary-1.12.2-1.3.4.757.jar                  | None                                     |
	| UCH   | roots               | 0.104                    | roots-2-0.104.jar                               | None                                     |
	| UCH   | librarianliblate    | 9.4                      | librarianlib-1.12.2-4.9.jar                     | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
Wizardry Plugin (wizardry-0.8.5.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz

**Comment by josephcsible** [comment]
To confirm whether this is actually caused by RFTools Dimensions, please try two tests:

1. Temporarily remove RFTools Dimensions, and try to reproduce the crash again but with the Nether or End in place of the RFTools dimension
2. Create a clean instance with just the mods you mentioned here, and try to reproduce the crash in a new world there

**Comment by McJty** [comment]
It is actually crashing in at vazkii.botania.client.model.GunModel.(GunModel.java:42)
though

**Comment by josephcsible** [comment]
Yeah, that's part of my suspicion that this isn't actually our crash.

**Comment by Henry-R** [comment]
I removed RFTools dimensions and tried to place the builder in the nether and when I want to change the settings in the quarry card the client crashed with the same error which is strange since I have Botania disabled in my instance. Give me a moment and I will test again with a clean instance

Crash Report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Wizardry Plugin (wizardry-0.8.5.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 4/8/18 10:35 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at vazkii.botania.client.model.GunModel.<init>(GunModel.java:42)
	at vazkii.botania.client.core.handler.MiscellaneousIcons.onModelBake(MiscellaneousIcons.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_324_MiscellaneousIcons_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at vazkii.botania.client.model.GunModel.<init>(GunModel.java:42)
	at vazkii.botania.client.core.handler.MiscellaneousIcons.onModelBake(MiscellaneousIcons.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_324_MiscellaneousIcons_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 56552192 bytes (53 MB) / 564428800 bytes (538 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2654 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                          | Signature                                |
	|:----- |:------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                 | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                 | 8.0.99.99                | forge-1.12.2-14.23.2.2654-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.2.2654             | forge-1.12.2-14.23.2.2654-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | astralsorcery       | 1.8.5                    | astralsorcery-1.12.2-1.8.5.jar                  | None                                     |
	| UCH   | quark               | r1.4-123                 | Quark-r1.4-123.jar                              | None                                     |
	| UCH   | autoreglib          | 1.3-16                   | AutoRegLib-1.3-16.jar                           | None                                     |
	| UCH   | baubles             | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCH   | betterbuilderswands | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | bibliocraft         | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCH   | botania             | r1.10-353                | Botania+r1.10-353.jar                           | None                                     |
	| UCH   | chisel              | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCH   | chiselsandbits      | 14.16                    | chiselsandbits-14.16.jar                        | None                                     |
	| UCH   | codechickenlib      | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | cucumber            | 1.1.0                    | cucumber-1.12-1.1.0.jar                         | None                                     |
	| UCH   | jei                 | 4.8.5.159                | jei_1.12.2-4.8.5.159.jar                        | None                                     |
	| UCH   | cyclicmagic         | 1.14.7                   | Cyclic-1.12.2-1.14.7.jar                        | None                                     |
	| UCH   | enderstorage        | 2.4.0.122                | EnderStorage-1.12-2.4.0.122-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | extraalchemy        | 0.3.8.2-release          | extraalchemy-0.3.8.2-release.jar                | None                                     |
	| UCH   | forgelin            | 1.6.0                    | Forgelin-1.6.0.jar                              | None                                     |
	| UCH   | llibrary            | 1.7.9                    | llibrary-1.7.9-1.12.2.jar                       | None                                     |
	| UCH   | iceandfire          | 1.4.0                    | iceandfire-1.4.0-1.12.2.jar                     | None                                     |
	| UCH   | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | wizardry            | 0.8.5                    | wizardry-0.8.5.jar                              | None                                     |
	| UCH   | librarianlib        | 9.4                      | librarianlib-1.12.2-4.9.jar                     | None                                     |
	| UCH   | mantle              | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCH   | mousetweaks         | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCH   | mysticalagriculture | 1.6.9                    | mysticalagriculture-1.12-1.6.9.jar              | None                                     |
	| UCH   | natura              | 1.12.2-4.3.2.42          | natura-1.12.2-4.3.2.42.jar                      | None                                     |
	| UCH   | xreliquary          | 1.12.2-1.3.4.757         | Reliquary-1.12.2-1.3.4.757.jar                  | None                                     |
	| UCH   | roots               | 0.104                    | roots-2-0.104.jar                               | None                                     |
	| UCH   | librarianliblate    | 9.4                      | librarianlib-1.12.2-4.9.jar                     | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
Wizardry Plugin (wizardry-0.8.5.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz

**Comment by Henry-R** [comment]
I tested with a clean instance with only 
<ul>
<li>Ender IO</li>
<li>EnderCore</li>
<li>McJtyLib</li>
<li>RFTools</li>
<li>RFTools Control</li>
<li>RFTools Dimensions</li>
<li>RFTools Power</li>
</ul>

Which all are the same versions I was using in my old world. I tested the builder in the overworld, the nether and a blank custom dimension without issue.

**Comment by josephcsible** [comment]
That seems to very strongly imply that this isn't an RFTools Dimensions issue. Report it to Botania's issue tracker.

**Comment by Henry-R** [comment]
Will do! Thanks for the help anyways.
