### ISSUE TITLE
Server crash on startup due to Dimension information for dimension X is missing!

### ISSUE THREAD

**Issue by Fatmice** [McJty/RFToolsDimensions#229]
Issue description: Server loads then crash when caught exception that information for dimension 3 was missing...I was just in dimension 3 before restarting server...

Steps to reproduce: 
You would need to load my [world](https://drive.google.com/uc?id=1h5A3Hirv3Q6Sz5d6f8QG7KqPsiMX3Ube&export=download
), which I can provide if requested.
*Added link to the entire server folder with world and mods.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.0.2
* RFTools: 1.12-7.54
* RFTools Dimensions: 1.12-5.60

Possibly incompatible mods: 
SpongeForge-1.12.2-2705-7.1.0-BETA-3266

Relevant logs, if any: 
https://gist.github.com/Fatmice/5f077e664a53b5550cb892b7316307c5

**Comment by josephcsible** [comment]
Can you reproduce this on a new world in the same modpack? How about in your world but without Sponge? Do you have an old backup of the world in case it got corrupt?

**Comment by Fatmice** [comment]
You can download the entire world, I've provided the link.  I don't have an older backup of the world.  This is a fresh world that I had to rebuild because rfttool dim corrupted my previous world for no apparent reason, giving my client a disconnect error and prevented me from logging in...Also dimension sometimes just won't stop ticking even if nobody is in it and there are no chunkloaders...this means you can't safedel them.

Anyways, I've found a work around.  Sponge will always load a world that it can load at startup then unloads them according to the world rules or global rules.  You can find them under config/sponge.  The funny thing is config/sponge/worlds/minecraft/overworld contains a duplicate entry of all folders found in config/sponge/worlds/rftoolsdim/rftools_dimension/.  Alas they are not deleted when you delete a world with either /rftdim safedel or dynamiting the realized dimension tab in the dimension editor block.  Removing the stale directories pertaining to dimension 3 did not solve the issue though.  Even setting the dimension to not be loaded at startup to false, i.e. load-on-startup=false in the world.conf, did not prevent the startup crash.

The reason? RFTOOLS3 folder was still lying around in the world folder.  Sponge was more than happy to read it up and load it (only to unload it later if it had loaded it) but this mod spits out exception because it can't find the dimension information and stopped everything.  Could you maybe do something more graceful than close the entire server?

Work around for me is to delete the RFTOOLS3 folder.

**Comment by Fatmice** [comment]
I should add that once the exception is raised and server forced stop, the world is entirely corrupted.  Removing the RFTOOLS3 folder from the world folder will allow server to startup but client will not be able to connect as they will get a client disconnect from "internal error"

**Comment by josephcsible** [comment]
If you don't have Sponge installed, can you still get the problem to happen from a good world?

**Comment by Fatmice** [comment]
I don't know, I never play without Sponge.

**Comment by josephcsible** [comment]
Can you try?

**Comment by Fatmice** [comment]
I used a backup world containing the dangling RFTOOLS3 folder in the world folder.  Loaded without Sponge and its plugins, world loaded with exceptions from this mod when running only Forge but did not forced close the server.

[15:22:45] [Server thread/ERROR] [FML]: Cannot Hotload Dim: 3
java.lang.IllegalArgumentException: Could not get provider type for dimension 3, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:149) ~[DimensionManager.class:?]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:236) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:832) [MinecraftServer.class:?]
	at codechicken.chunkloader.manager.ChunkLoaderManager.getWorld(ChunkLoaderManager.java:505) [ChunkLoaderManager.class:?]
	at codechicken.chunkloader.manager.ChunkLoaderManager$ChunkLoaderOrganiser.revive(ChunkLoaderManager.java:326) [ChunkLoaderManager$ChunkLoaderOrganiser.class:?]
	at codechicken.chunkloader.manager.ChunkLoaderManager$PlayerOrganiser.revive(ChunkLoaderManager.java:390) [ChunkLoaderManager$PlayerOrganiser.class:?]
	at codechicken.chunkloader.manager.ChunkLoaderManager.processLoaderStates(ChunkLoaderManager.java:693) [ChunkLoaderManager.class:?]
	at codechicken.chunkloader.manager.ChunkLoaderManager.onTickEnd(ChunkLoaderManager.java:670) [ChunkLoaderManager.class:?]
	at codechicken.chunkloader.handler.ChunkLoaderEventHandler.worldTick(ChunkLoaderEventHandler.java:32) [ChunkLoaderEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1034_ChunkLoaderEventHandler_worldTick_WorldTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by josephcsible** [comment]
I meant can you make the corruption happen without Sponge, not will the already-corrupted world load without Sponge.

**Comment by Fatmice** [comment]
I don't know how to make such thing...the best I have is a world that loaded fine prior to this event while running Sponge.  That's what I used for the previous comment.
