### ISSUE TITLE
Dimlet Null Point Exception

### ISSUE THREAD

**Issue by Fatmice** [McJty/RFToolsDimensions#231]
Issue description: 
[main/ERROR] [mcjty.lib.varia.Logging]: Catching
java.lang.NullPointerException: id
	at mcjty.rftoolsdim.dimensions.dimlets.DimletKey.<init>(DimletKey.java:21) ~[DimletKey.class:?]
	at mcjty.rftoolsdim.dimensions.dimlets.KnownDimletConfiguration.getDimletKey(KnownDimletConfiguration.java:357) ~[KnownDimletConfiguration.class:?]
	at mcjty.rftoolsdim.items.KnownDimlet.func_77653_i(KnownDimlet.java:155) ~[KnownDimlet.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617) ~[aip.class:?]
	at moze_intel.projecte.utils.ItemSearchHelper$DefaultSearch.doesItemMatchFilter_(ItemSearchHelper.java:42) ~[ItemSearchHelper$DefaultSearch.class:?]
	at moze_intel.projecte.utils.ItemSearchHelper.doesItemMatchFilter(ItemSearchHelper.java:20) ~[ItemSearchHelper.class:?]
	at moze_intel.projecte.gameObjs.container.inventory.TransmutationInventory.updateClientTargets(TransmutationInventory.java:228) ~[TransmutationInventory.class:?]
	at moze_intel.projecte.gameObjs.container.inventory.TransmutationInventory.<init>(TransmutationInventory.java:59) ~[TransmutationInventory.class:?]
	at moze_intel.projecte.utils.GuiHandler.getClientGuiElement(GuiHandler.java:206) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:276) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:111) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43) ~[OpenGuiHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2747
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.0.3
* RFTools: 1.12-7.55
* RFTools Dimensions: 1.12-5.60

Possibly incompatible mods: 
SpongeForge, OptiFine

Relevant logs, if any: 
https://paste.ee/p/PIAXB

**Comment by josephcsible** [comment]
Can you reproduce this without ProjectE installed?

**Comment by Fatmice** [comment]
I do not recall...I'll close this for now as I do not recall how it was produced.
