### ISSUE TITLE
Game crash entering singleplayer game

### ISSUE THREAD

**Issue by Garagoth** [McJty/RFToolsDimensions#243]
Issue description: 
Game crashes when loading previously working world.
More, in this save there are NO rftools dimensions created.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2772
* CompatLayer (only if on Minecraft 1.10 or 1.11): n/a
* McJtyLib: 3.0.6
* RFTools: 7.57 
* RFTools Dimensions: 5.62

Crash:
https://pastebin.com/E1zf5fun

Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.<init>(GenericChunkGenerator.java:215)
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.func_186060_c(GenericWorldProvider.java:356)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:848)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:118)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:102)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

**Comment by josephcsible** [comment]
> More, in this save there are NO rftools dimensions created.

That seems unlikely given the stack trace you got. Are you sure about this? Anyway, two things to try:

1. See if you can create a new saved game, create an RFTools dimension, go there, save and exit while there, then reload it without crashing
2. Make a backup of the bad world, then try loading it with just RFTools Dimensions and its dependencies installed

**Comment by Garagoth** [comment]
Yes, 100% sure I did not create any dimensions. There are no necessary machines placed even and never were. I am mildly confident that this is first load of this save with rftools dimensions installed...

I will try 1 and 2 in a while (takes time obviously).

**Comment by Garagoth** [comment]
I noticed that there is an empty folder in saves/MySave/ called RFTOOLS3.
Not a single file was there. When I removed it save loaded with no issues.

EDIT: Uh, no, scratch this out. Still happening. The directory got created again when saving game, still empty. Cannot start that save, now gives me:
```
[Server thread/ERROR] [mcjty.lib.varia.Logging]: Catching
java.lang.RuntimeException: Dimension information for dimension 3 is missing!
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.getDimensionInformation(GenericWorldProvider.java:91) [GenericWorldProvider.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.createBiomeProviderInternal(GenericWorldProvider.java:229) [GenericWorldProvider.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.func_76572_b(GenericWorldProvider.java:220) [GenericWorldProvider.class:?]
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40) [aym.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116) [oo.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18) [ok.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:102) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

followed by

```
[Server thread/INFO] [mcjty.lib.varia.Logging]: Error: setSeed() called with null diminfo. Error ignored!
[Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.<init>(GenericChunkGenerator.java:215) ~[GenericChunkGenerator.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.func_186060_c(GenericWorldProvider.java:356) ~[GenericWorldProvider.class:?]
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:848) ~[oo.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:118) ~[oo.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18) ~[ok.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:102) ~[chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

Even better, the same happens if I just:
create new world
save and quit
try to load it again

**Comment by Garagoth** [comment]
It seems like removing Advanced Rocketry mod makes this problem go away. Weird?

**Comment by McJty** [comment]
Looks like a dimension conflict between both mods. Was advanced rocketry added later?

**Comment by Garagoth** [comment]
No, RFTools Dimensions were added later, however this did not happen on server, happened on client after both mods were added and AR was then updated.
Is there anything I can get to help here? Not sure where to look next.

EDIT:
I wasn't able to reproduce it with a clean install of AR and RFTools Dimensions only.
So something mote then just AR might be interfering.

**Comment by Cazadorsniper** [comment]
We're not using AR and this crash happens in PO3. Anytime one of our testers join the testing server then exit to create a singleplayer world, this crash happens.

**Comment by josephcsible** [comment]
@Cazadorsniper your issue is a duplicate of #205 and is unrelated to this issue.

**Comment by Cazadorsniper** [comment]
Yeah, noticed that after I commented.

**Comment by Yarillo4** [comment]
Same error here on All the Mods 3 - Remix 1.5.2. Singleplayer crashes but multiplayer works

https://www.curseforge.com/minecraft/modpacks/all-the-mods-3-remix

The crash happens when loading any world. I've tested on an old Vanilla save downloaded from the internet and on a brand new save

* RFTools: 7.72
* RFToolsDim: 5.71
* Forge: 14.23.5.2847
* MCJtyLib: 3.5.4

https://paste.dimdev.org/ohinutufuf.mccrash

When I disable Advanced Rocketry, the crash goes away

**Comment by jdratlif** [comment]
I am not using Advanced Rocketry, but I also get a crash like this.

https://paste.dimdev.org/yuluhozebi.mccrash

**Comment by xGarionx** [comment]
https://paste.dimdev.org/woyefadifu.mccrash
And another one of these .

- rft Tools 7.73
- rft dim 5.71
- forge 2847
- JtyLib 3.5.4
Modpack : A.C.P

All people on the server have this issue, however this crash only appears in the modpack after entering a Multiplayer World and then open a Single Player

**Comment by jdratlif** [comment]
I couldn't narrow it down to when it would crash until you said that @xGarionx , but that's what is happening to us as well. If I start the game, things work fine. It's only if I try to quit mulitplayer and go into single player that I get  the crash.

**Comment by puchm** [comment]
I also had this problem in the MC Eternal modpack. Modpack version is 1.3.7 with the following mods added: 

- BrandonsCore 2.4.19.214
- Draconic Additions 1.14.1.37
- Draconic Evolution 2.3.27.353

Also only happens in singleplayer, not in multiplayer. It also happens when creating a new singleplayer world - I can't play singleplayer at all because of this. Removing the `RFTOOLS3` folder within the world save as suggested before didn't change anything.

Important to note: This started happening today - yesterday everything worked just fine. I did not manually update anything, nor did my launcher. Does RFTools / RFTools Dimensions have some sort of automatic update? Maybe the modpack also has an automatic update but I don't think so. I will ask on their discord though.

Here's one of the many crash reports I got:

[crash-2020-11-27_19.46.51-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/5609254/crash-2020-11-27_19.46.51-server.txt)

**Comment by Atricos** [comment]
This exact crash also happens on the (upcoming) Divine Journey 2 modpack.

From what we've been able to test:
- **The crash only happens when the player loads up the game, goes into a Multiplayer world, leaves, then tries to enter an existing or new Singleplayer world.**
- The crash **doesn't occur** if the player loads up the game, first joins a Singleplayer world, leaves, joins a Multiplayer world, leaves again, and joins a Singleplayer world for the second time. From this it's safe to deduce that **some variable is being set whenever the player first joins any world**, and if this variable is set on a Multiplayer world, it'll be incompatible with a Singleplayer world.

It crashes on this line every time: https://github.com/McJtyMods/RFToolsDimensions/blob/1.12/src/main/java/mcjty/rftoolsdim/dimensions/world/GenericChunkGenerator.java#L215

And it's always a NullPointerException, it seems like `.getTerrainType()` is returning `null`. I'm not familiar with the code enough to make further conclusions, but seeing as this is happening throughout multiple modpacks, it would be nice to get a fix.

If anyone's smart enough to make a Pull Request for this, I'll be forever greatful to you.

**Comment by McJty** [comment]
It's very weird that this suddenly starts happening because I've had no reports of this for RFTools Dimensions on 1.12 for ages. So I suspect some other mod is doing something bad. It's not easy to fix this. Just adding an if null test is not enough because if that information is missing then something more fundamental is wrong.

Also I no longer work on 1.12

**Comment by Atricos** [comment]
Seeing as RFTools Dimensions for 1.12.2 hasn't been updated for 2 years, but the crash only started occuring now, it has to be caused by a mod that has recently been updated, and is included in the modpacks mentioned above.

Edit: Though the original comment from this thread is from 2018, so maybe not.

**Comment by Atricos** [comment]
We've been able to deduce that the missing information comes from **Galacticraft's Space Station** dimension, and it only starts happening once someone loaded the dimension for the first time.

This is from a `log` file, right as the crash occured:
```
[19:13:13] [Server thread/ERROR]: Catching
java.lang.RuntimeException: Dimension information for dimension 3 is missing!
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.getDimensionInformation(GenericWorldProvider.java:91) [GenericWorldProvider.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.createBiomeProviderInternal(GenericWorldProvider.java:229) [GenericWorldProvider.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.init(GenericWorldProvider.java:220) [GenericWorldProvider.class:?]
	at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:40) [aym.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116) [oo.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18) [ok.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:126) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:156) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```
And `/forge dimensions` shows that it's the "Space Station" dimension. This pack only has Galacticraft (not Advanced Rocketry), so that has to be the Galacticraft Space Station dimension:
![image](https://user-images.githubusercontent.com/24854267/128894709-3092ece9-f59b-4058-ade2-33d2657eae56.png)

Possible cause: The client has the Space Station dimension loaded as an existing world, possibly in Cache/RAM, but it doesn't yet exist on Singleplayer, so when RFTools tries to load it, it fails.

**Comment by Atricos** [comment]
Turns out **it IS a dimension ID conflict**.

- On the server we're playing on, someone created an RFTools Dimension with **ID 3** (the first unoccupied ID), and when using `/forge dimensions`, it shows `rftools_dimension: {3}`, (as opposed to `{5, 6}`, like on the above picture, which was taken in a Singleplayer world).
- But **the Galacticraft Space Stations also work on the same premise as RFTools Dimensions**, **"space stations will start at ID 2 and go up skipping IDs that are already used by other mods"**.

**The reason for the crash:** Both Galacticraft and RFTools Dimensions think ID 3 is available, (for a personal Space Station or an RFTools Dimension). The Space Station ID gets cached from the server, and when entering a Singleplayer world, RFTools Dimensions thinks it's available, so it tries to do something with it (pregenerate it?), but fails, because it already exists.

I'm not sure if this is on RFTools Dimensions or Galacticraft.

**Possible workarounds:**
- Disable Space Stations in `config/Galacticraft/core.conf`, line 219: `B:"Disable Space Station creation"=true`
- Or, when creating a server, have each player that would ever visit the server first go to their Space Station dimension before ever creating an RFTools Dimension. There can be any number of Space Station dimensions, which would cause further conflicts. (Obviously, not possible on a public server.)
- On the Galacticraft dev side, make the default Space Station IDs negative numbers, maybe going down from -1, -2, ... etc. (or allow the players to change the IDs). (Though Galacticraft issues have been archived, so I can't even report it there: https://github.com/micdoodle8/Galacticraft/issues)
- (On the RFTools Dimensions dev side, check if any dimension IDs are cached, before trying to pregen a dimension? - not sure about this one)
