### ISSUE TITLE
problems with a modpack crashing, confirmed to be RFTools Dimensions

### ISSUE THREAD

**Issue by SolThePupper** [McJty/RFToolsDimensions#272]
Issue description: I'm trying to play the Enigmatica 2: Expert Skyblock mudpack. every time I start it up, it crashes partway through initialization. after figuring out how to find the actual crash report, it said it was an exception from RFTools Dimensions. I tried it again with this mod disabled, and it successfully loaded for the first time. However, I need Dimensions since I'll be playing on a server and will need it installed. 

Steps to reproduce: I have no idea, but I will post what  it says in the crash log, as long as it may be right below this.
"Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools Dimensions (rftoolsdim)
Caused by: java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106)
	at mcjty.rftoolsdim.config.DimletRules.readRulesFromFile(DimletRules.java:146)
	at mcjty.rftoolsdim.config.DimletRules.readRulesFromFile(DimletRules.java:134)
	at mcjty.rftoolsdim.config.DimletRules.readRules(DimletRules.java:89)
	at mcjty.rftoolsdim.setup.ModSetup.preInit(ModSetup.java:45)
	at mcjty.rftoolsdim.RFToolsDim.preInit(RFToolsDim.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)"

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* McJtyLib: don't know what this is or where to find it
* RFTools: 
* RFTools Dimensions: 

Possibly incompatible mods: I had Optifine, but the same thing happened without it. As stated in the description, the pack loaded perfectly without this mod enabled.

**Comment by McJty** [comment]
There is a problem in your dimlets.json file. Did you edit that or get that from anywhere?

**Comment by josephcsible** [comment]
In either case, please upload your dimlets.json file here, and we can try to point out the mistake in it.

**Comment by SolThePupper** [comment]
Well 2 things: first off, I don't know how to upload the dimlets.json file since Github doesn't let me upload json files. Second of all, I  did  not edit it or get it separately.

**Comment by McJty** [comment]
Well you could upload it to a pastebin (bpaste, pastebin) or make a gist. Alternatively you could just delete it and let rftools dimensions generate it again

**Comment by SolThePupper** [comment]
So if I delete it it should start working?

**Comment by josephcsible** [comment]
Yes.

**Comment by SolThePupper** [comment]
Thanks for the help, it worked perfectly

**Comment by TRPXD** [comment]
where is the file i have the same problem

**Comment by McJty** [comment]
configs folder
