### ISSUE TITLE
crash when loading dimension without stronghold structure dimlet

### ISSUE THREAD

**Issue by Cheos137** [McJty/RFToolsDimensions#273]
Issue description: 
when creating a dimension without a stronghold structure dimlet and then loading it via teleporting to it (via commands (either forge or rft; doesn't matter)) or generating chunks in it via forge commands, the game crashes. And the dimension wouldn't even show up in the dialing device.
When you however create a dimension with the stronghold structure dimlet installed, everything works just fine.
Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2837
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.5.4
* RFTools: 7.72
* RFTools Dimensions: 5.71

Possibly incompatible mods: 
RandomPatches

Relevant logs, if any: 
out of crash-report.txt:
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:141)
	at net.minecraft.world.gen.structure.MapGenStronghold.func_180706_b(MapGenStronghold.java:77)
	at ivorius.reccomplex.world.gen.feature.structure.MapGenStructureHook.func_180706_b(MapGenStructureHook.java:115)
	at ivorius.reccomplex.events.handlers.RCTerrainGenEventHandler$5.func_180706_b(RCTerrainGenEventHandler.java:323)
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.func_180513_a(GenericChunkGenerator.java:772)
	at com.gw.dm.util.DMGenerationHandler.generateTraps(DMGenerationHandler.java:45)
	at com.gw.dm.util.DMGenerationHandler.generate(DMGenerationHandler.java:37)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraftforge.server.command.ChunkGenWorker.doWork(ChunkGenWorker.java:165)
	at net.minecraftforge.common.WorldWorkerManager.tick(WorldWorkerManager.java:51)
	at net.minecraftforge.common.ForgeInternalHandler.onServerTick(ForgeInternalHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_616_ForgeInternalHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

out of latest.log:
[Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@67b689b0:
java.lang.NullPointerException: null
	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:141) ~[bbs.class:?]
	at net.minecraft.world.gen.structure.MapGenStronghold.func_180706_b(MapGenStronghold.java:77) ~[bbs.class:?]
	at ivorius.reccomplex.world.gen.feature.structure.MapGenStructureHook.func_180706_b(MapGenStructureHook.java:115) ~[MapGenStructureHook.class:?]
	at ivorius.reccomplex.events.handlers.RCTerrainGenEventHandler$5.func_180706_b(RCTerrainGenEventHandler.java:323) ~[RCTerrainGenEventHandler$5.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.func_180513_a(GenericChunkGenerator.java:772) ~[GenericChunkGenerator.class:?]
	at com.gw.dm.util.DMGenerationHandler.generateTraps(DMGenerationHandler.java:45) ~[DMGenerationHandler.class:?]
	at com.gw.dm.util.DMGenerationHandler.generate(DMGenerationHandler.java:37) ~[DMGenerationHandler.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167) ~[GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990) ~[axw.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at net.minecraftforge.server.command.ChunkGenWorker.doWork(ChunkGenWorker.java:165) ~[ChunkGenWorker.class:?]
	at net.minecraftforge.common.WorldWorkerManager.tick(WorldWorkerManager.java:51) ~[WorldWorkerManager.class:?]
	at net.minecraftforge.common.ForgeInternalHandler.onServerTick(ForgeInternalHandler.java:90) ~[ForgeInternalHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_616_ForgeInternalHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

[Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:141) ~[bbs.class:?]
	at net.minecraft.world.gen.structure.MapGenStronghold.func_180706_b(MapGenStronghold.java:77) ~[bbs.class:?]
	at ivorius.reccomplex.world.gen.feature.structure.MapGenStructureHook.func_180706_b(MapGenStructureHook.java:115) ~[MapGenStructureHook.class:?]
	at ivorius.reccomplex.events.handlers.RCTerrainGenEventHandler$5.func_180706_b(RCTerrainGenEventHandler.java:323) ~[RCTerrainGenEventHandler$5.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.func_180513_a(GenericChunkGenerator.java:772) ~[GenericChunkGenerator.class:?]
	at com.gw.dm.util.DMGenerationHandler.generateTraps(DMGenerationHandler.java:45) ~[DMGenerationHandler.class:?]
	at com.gw.dm.util.DMGenerationHandler.generate(DMGenerationHandler.java:37) ~[DMGenerationHandler.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167) ~[GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990) ~[axw.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at net.minecraftforge.server.command.ChunkGenWorker.doWork(ChunkGenWorker.java:165) ~[ChunkGenWorker.class:?]
	at net.minecraftforge.common.WorldWorkerManager.tick(WorldWorkerManager.java:51) ~[WorldWorkerManager.class:?]
	at net.minecraftforge.common.ForgeInternalHandler.onServerTick(ForgeInternalHandler.java:90) ~[ForgeInternalHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_616_ForgeInternalHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by McJty** [comment]
Not something I can fix on my side I'm afraid. I also see Recurrent Complex in the stack trace
