### ISSUE TITLE
Dimension Crash; NullPointerException

### ISSUE THREAD

**Issue by kimjosephdo** [McJty/RFToolsDimensions#284]
Issue description: Game crashing when entering dimensions; happens at various places, such as underneath the spawn platform and as soon as the player spawns

Steps to reproduce: Not sure; happens at different random places

Versions:
FTB Infinity Evolved
* Minecraft: 1.7.10
* Forge: 7.10.99.99
* RFTools:4.23

Possibly incompatible mods: 

Relevant logs, if any: 
java.lang.NullPointerException: Unexpected error
	at mrtjp.relocation.MovementManager2$.getWorldStructs(movement.scala:32)
	at mrtjp.relocation.MovementManager2$.isMoving(movement.scala:105)
	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:20)
	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:807)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1712)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1388)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by josephcsible** [comment]
1. Minecraft 1.7.10 is no longer supported.
2. This crash looks like it was caused by MrTJP's Forge Relocation mod, not this mod.
