### ISSUE TITLE
[1.10.2] Error while removing dimension with safedel

### ISSUE THREAD

**Issue by MadMax-XIII** [McJty/RFToolsDimensions#29]
Using  rftoolsdim-1.10-4.30beta47.jar, rftools-1.10-5.20.jar and mcjtylib-1.10-1.9.9.jar (AllTheMods modpack v1.17 on  forge 12.18.1.2073) I get this error whenever I try to remove an RFTools dimension with /rftdim safel:

`[20:59:12] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[20:59:12] [Server thread/WARN]: Couldn't process command: 'rftdim safedel 5'
java.lang.IllegalArgumentException: Failed to unregister dimension for id 5; No provider registered
        at net.minecraftforge.common.DimensionManager.unregisterDimension(DimensionManager.java:118) ~[DimensionManager.class:?]
        at mcjty.rftoolsdim.dimensions.RfToolsDimensionManager.removeDimension(RfToolsDimensionManager.java:341) ~[RfToolsDimensionManager.class:?]
        at mcjty.rftoolsdim.commands.CmdSafeDelete.execute(CmdSafeDelete.java:84) ~[CmdSafeDelete.class:?]
        at mcjty.rftoolsdim.commands.DefaultCommand.func_184881_a(DefaultCommand.java:111) ~[DefaultCommand.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]`

The dimension is removed from all dialing devices, but there's still RFTOOLSx folders in my world save and I'm unsure if I can safely remove them.

**Comment by McJty** [comment]
You can safely remove RFTOOLS folders if you deleted the corresponding dimension. I'll check out why it gave an error though

**Comment by McJty** [comment]
Fixed next release
