### ISSUE TITLE
Looking at dimlets in item frames or in chests causes an internal server error

### ISSUE THREAD

**Issue by VIIJordon** [McJty/RFToolsDimensions#296]
Issue description: when i enter a new dimension i am generally fine until i stumble upon a dimlet building, when i go to look at the item frame or in the chest which houses dimensions, my game crashes. I am playing on a server, and it doesnt shut down the server, just kicks me.

I am in a custom mod pack, with several mods on it, but none that i can clearly see interfering

Steps to reproduce: 

-load into dimension
-walk into dimlet building
-look at dimlet on wall or in chest
-game crashes

Versions:
* Minecraft: 1.12.2
* Forge: 12.23.5.2854
* McJtyLib: 3.5.4
* RFTools: 7.73
* RFTools Dimensions: 5.71

Relevant logs, if any: 

Crash Report:

https://pastebin.com/BNhEt19S

**Comment by Shotguun29** [comment]
same here bro, error code ArrayIndexOutOfBoundsException: 10

**Comment by Shotguun29** [comment]
ava.lang.ArrayIndexOutOfBoundsException: 10
	at de.kitsunealex.silverfish.item.ItemBlockBase.func_77667_c(ItemBlockBase.java:59)
	at net.minecraft.item.Item.func_77657_g(Item.java:292)
	at net.minecraft.item.Item.func_77653_i(Item.java:362)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at mcjty.rftoolsdim.dimensions.DimensionInformation.getDisplayName(DimensionInformation.java:625)
	at mcjty.rftoolsdim.dimensions.dimlets.KnownDimletConfiguration.getDisplayName(KnownDimletConfiguration.java:420)
	at mcjty.rftoolsdim.items.KnownDimlet.func_77653_i(KnownDimlet.java:160)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraftforge.client.GuiIngameForge.renderToolHighlight(GuiIngameForge.java:648)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:172)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by Shotguun29** [comment]
so i had the item in my hand when it crashed the game, i would reload the game and it would crash on start up. The way i fixed it was to uninstall the mod, load it up and it worked. (yes I lost all items, and It respond me in the overworld, thank god)
