### ISSUE TITLE
[1.8.9] Server crash

### ISSUE THREAD

**Issue by iarspider** [McJty/RFToolsDimensions#3]
I have created a random dimension (which turned out to be an ocean of liquid death from Thaumcraft, as far as I could see before crashing), and the server crashed: http://paste.ubuntu.com/15100697/

Now I can't log back in - the server crashes immediately on logon. 

I can see the following error in client log:
```
[18:45:35] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at mcjty.rftoolsdim.dimensions.RfToolsDimensionManager.getDimensionManager(RfToolsDimensionManager.java:296) ~[RfToolsDimensionManager.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.getDimensionInformation(GenericWorldProvider.java:66) ~[GenericWorldProvider.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.func_76572_b(GenericWorldProvider.java:163) ~[GenericWorldProvider.class:?]
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:37) ~[anm.class:?]
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:55) ~[bdb.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:249) ~[bcy.class:?]
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:76) ~[gt.class:?]
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13) ~[gt.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 17 more
```

Forge 1724, McJtyLib 1.8.1beta6, RFTools 4.22beta18, RFTools dimensions 4.22beta20

UPD: Updating RFTools to beta20 and dimensions to beta21 did not help.

**Comment by iarspider** [comment]
Probably an unlucky combination of dimlets. Saved copy of dat files: 
https://dl.dropboxusercontent.com/u/8105640/RFToolsDimensionManager.dat 
https://dl.dropboxusercontent.com/u/8105640/RFToolsDimensionStorage.dat

**Comment by McJty** [comment]
Update RFTools. That bug has been fixed in that mod
