### ISSUE TITLE
Receiver wasn't created, manual dimension TP causes client crash

### ISSUE THREAD

**Issue by Bidgam** [McJty/RFToolsDimensions#310]
Latest 1.16.5 of MC, Forge 36.0.15 plus rftoolsdim-1.16-7.0.1-beta.

Related to this reddit discussion: https://www.reddit.com/r/feedthebeast/comments/ldq9e5/first_alpha_release_of_rftools_dimensions_for_1164/gnyvnli/?utm_source=reddit&utm_medium=web2x&context=3

1. I created a random dimension normally but no receiver was created. The list of dimensions also doesn't show except for the overworld (though in the server files it did created the random dimension).

2. I then attempted a manual TP to that dimension but the client produced this error: "Connection Lost - Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Missing Dimension ResourceKey[minecraft:dimension / rftoolsdim:random001]

**Comment by Bidgam** [comment]
Which version of mctjylib is necessary for this beta of dimensions? Going to check on that.

**Comment by McJty** [comment]
Latest, always latest

**Comment by Bidgam** [comment]
Updating it to the latest didn't let it see it in the Dialing Device still unfortunately.

I tried removing the dimension directory and creating a new random tab, but it keeps wanting to refer back to random001 (the original world I created).

I also tried removing the dimension folder again, restarting the server, and it recreated that same dimension folder random001... from somewhere. I don't even have a tab now for it so I have no idea how it knew.

**Comment by lendrick** [comment]
I'm having a similar issue, running the latest rftools and mcjtylib mods along with forge 36.0.40.  

The update fixes the missing teleporter issue, but that doesn't seem to be the entire problem.  I also get this error on the client side when I teleport to the dimension the first time:

```
[24Feb2021 02:45:23.014] [Netty Epoll Server IO #2/ERROR] [net.minecraft.network.NettyPacketEncoder/]: Error encoding packet
java.lang.RuntimeException: Missing Dimension ResourceKey[minecraft:dimension / rftoolsdim:blah]
	at com.qouteall.immersive_portals.dimension_sync.DimensionIdRecord.getIntId(DimensionIdRecord.java:39) ~[immersive_portals:0.15-mc1.16.5-forge]
	at com.qouteall.immersive_portals.dimension_sync.DimId.writeWorldId(DimId.java:24) ~[immersive_portals:0.15-mc1.16.5-forge]
	at net.minecraft.network.play.server.SPlayerPositionLookPacket.handler$zjm000$onWrite(SourceFile:530) ~[?:?]
	at net.minecraft.network.play.server.SPlayerPositionLookPacket.func_148840_b(SourceFile:52) ~[?:?]
	at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:38) ~[?:?]
	at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:12) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at net.minecraft.network.NetworkManager.lambda$dispatchPacket$5(NetworkManager.java:196) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) [server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [server-1.16.5-20210115.111550-extra.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```

If I reconnect to the server after being booted off, the server crashes with the attached error.

Once I restart the server, I find myself in the new dimension and can teleport there and back from then on, but I have to go through this process for each dimension I create.
[crashlog.txt](https://github.com/McJtyMods/RFToolsDimensions/files/6033072/crashlog.txt)

**Comment by Bidgam** [comment]
For my particular instance, just double checking that having the mod Versatile Portals isn't somehow messing with the dimensions system...

https://www.curseforge.com/minecraft/mc-mods/versatile-portals

**Comment by McJty** [comment]
> Updating it to the latest didn't let it see it in the Dialing Device still unfortunately.
> 
> I tried removing the dimension directory and creating a new random tab, but it keeps wanting to refer back to random001 (the original world I created).
> 
> I also tried removing the dimension folder again, restarting the server, and it recreated that same dimension folder random001... from somewhere. I don't even have a tab now for it so I have no idea how it knew.

As has always been the case. The same sequence of dimlets ALWAYS points back to the same dimension. Use digit dimlets to make new unique dimensions

**Comment by McJty** [comment]
@lendrick Seems to be Immersive Portals having issues:

	at com.qouteall.immersive_portals.dimension_sync.DimensionIdRecord.getIntId(DimensionIdRecord.java:39) ~[immersive_portals:0.15-mc1.16.5-forge]
	at com.qouteall.immersive_portals.dimension_sync.DimId.writeWorldId(DimId.java:24) ~[immersive_portals:0.15-mc1.16.5-forge]

**Comment by Bidgam** [comment]
I'm going to remove that same mod I have and see if it resolves my issue too. Will let you know.

**Comment by lendrick** [comment]
I can confirm that removing Immersive Portals fixed it.

Too bad, it's a cool mod, but I was only using it for one nether portal, so oh well. :)

**Comment by McJty** [comment]
Maybe you should report this so that we can perhaps work out a fix? Could be on both sides

**Comment by Bidgam** [comment]
Good idea to let them know. I haven't had a chance to check my particular
issue yet, but I'll do the same if it is confirmed.

**Comment by Bidgam** [comment]
I removed Immersive Portals and nothing changed for me. In fact, I can't even create dimensions anymore, they just don't show up except for the very original Random001 which no longer adds the files for the dimension to the server folder. It says it's 'ready', but it's definitely not. Still doesn't show in the dialing device either.

I may need to reset the mod somehow entirely. Would you recommend I remove it and run the server, then add it back and run it again? How can I 'clear it out'? Seems I may need to do that next.

Thanks

**Comment by Bidgam** [comment]
This can get closed. I reinstalled the modpack fresh within Immersive Portals and it worked.
