### ISSUE TITLE
Checker biome controller has odd behavior

### ISSUE THREAD

**Issue by misterfool** [McJty/RFToolsDimensions#337]
Issue description:

When I try to use the checker biome controller, it has this [odd behavior](https://pasteboard.co/JT63vHS.png)

Steps to reproduce: 

Here is the [setup](https://pasteboard.co/JT64UwL.png). It would be so nice to have documentation of this domain specific language. 

 
Versions:
* Minecraft: 1.16.5
* Forge: 36.0.46
* McJtyLib: 1.16-5.0.18
* RFTools: 1.16-2.0.10 (assuming you mean 'base')
* RFTools Dimensions: 1.16-7.0.4-beta
 
Thanks in advance for looking into this.

**Comment by McJty** [comment]
Do you have Immersive Portals and/or optifine

**Comment by misterfool** [comment]
I have neither.

**Comment by McJty** [comment]
Would be nice to get the actual dimlets. Can't see much from just icons

**Comment by McJty** [comment]
Also you're not using the latest version of RFTools Dimensions

**Comment by misterfool** [comment]
I have found that it doesn't really matter what the blocks or biomes are, "checker" is more like "striper". Anyway, the dimlets are:

- water
- stone block
- dirt block
- plains
- stone block
- dirt block
- ocean
- attribute: default
- terrain: default
- feature: default
- time: day
- biome controller: checker

The version I have is the one currently in a number of modpacks, including allthemods, sporia, and direwolf20. If there is a newer one, I can test with that.

**Comment by misterfool** [comment]
So going to 7.0.6 beta, I got curious and typed "terrain" in the dimlet workbench in my creative world and this happened:

```
[18Mar2021 23:10:12.988] [Render thread/FATAL] [net.minecraft.client.Minecraft/]: Reported exception thrown!
net.minecraft.crash.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:505) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.46-launcher.jar:36.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchMethodError: mcjty.lib.varia.Tools.getModName(Lnet/minecraftforge/registries/IForgeRegistryEntry;)Ljava/lang/String;
	at mcjty.rftoolsdim.modules.dimlets.data.DimletTools.getReadableName(DimletTools.java:305) ~[rftoolsdim:1.16-7.0.6-beta]
	at mcjty.rftoolsdim.modules.workbench.client.GuiWorkbench.dimletMatches(GuiWorkbench.java:232) ~[rftoolsdim:1.16-7.0.6-beta]
	at mcjty.rftoolsdim.modules.workbench.client.GuiWorkbench.lambda$updateList$0(GuiWorkbench.java:220) ~[rftoolsdim:1.16-7.0.6-beta]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_281]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.ReferencePipeline.forEachOrdered(Unknown Source) ~[?:1.8.0_281]
	at mcjty.rftoolsdim.modules.workbench.client.GuiWorkbench.updateList(GuiWorkbench.java:222) ~[rftoolsdim:1.16-7.0.6-beta]
	at mcjty.rftoolsdim.modules.workbench.client.GuiWorkbench.func_230450_a_(GuiWorkbench.java:253) ~[rftoolsdim:1.16-7.0.6-beta]
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:88) ~[?:?]
	at mcjty.lib.gui.GenericGuiContainer.func_230430_a_(GenericGuiContainer.java:261) ~[mcjtylib:1.16-5.0.18]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:296) ~[forge:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?]
	... 22 more
```

**Comment by McJty** [comment]
You must update McJtyLib too

**Comment by misterfool** [comment]
Done, and no more crashes. Regenerated a dimension using the above dimlet sequence and ... it appears to be the same result.

**Comment by Braidey** [comment]
I've also come across this issue with the striping. I've also noticed that if you set your biome controller to default it overwrites any individual biomes you've added to your dimlet
