### ISSUE TITLE
[1.16.5] Can't dial any dimension

### ISSUE THREAD

**Issue by 755437985** [McJty/RFToolsDimensions#345]
Issue description:
Tried dialing any created dimension but failed with the info 'Invalid desitination!'
![javaw_kzSXJNS96c](https://user-images.githubusercontent.com/25640242/113476283-2838db80-94ad-11eb-91be-015648bcd332.png)

Steps to reproduce:
Create a dimension tab with a digit dimlet
Setup the dialing device and dial the created dimension

Versions:
* Minecraft: 1.16.5
* Forge: 36.1.4
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:5.0.19
* RFTools:2.0.10
* RFTools Dimensions: 7.0.7

logs after I clicked the 'Dial' button:
[log](https://pastebin.com/AkBucuHq)

**Comment by McJty** [comment]
You put the dimension tab in the dimension builder and let it fully charge up?

**Comment by 755437985** [comment]
Yes, tried with only rftools and it worked.
Also I tested it with every single mod in my pack and it works well.
It's not working when I put all the mods in, so I dont know which mod or mods combination causes that.

**Comment by 755437985** [comment]
I teleported to the created dimension using vanilla command and find that the receiver was replaced by a command block.
When I manually place a receiver at where it should be, I can't open its GUI. 
![javaw_uDjlU33fgW](https://user-images.githubusercontent.com/25640242/113560188-2c900080-9635-11eb-8a04-a0344298acb5.png)

**Comment by Zang518** [comment]
I have also encounter this problem as well in the Direwolf20 1.16 FTB pack ver1.7.0, rftoolsdim-1.16-7.0.4-beta.jar on forge 36.0.45. I have tried in 3 different saves receiving the same error. In the error, I do see optifine and appliedenergetics2 mentioned but I'm not an avid java error reader so I only sometimes get the jest of what I'm looking at. The dimlet I used is just a random world. No customization, just creating an empty dimension tab, naming it in the enscriber, putting it in the dimension builder to let it charge. Every time I click the dial button to that dimension, I get the invalid destination error and the error below is in the game log for each time I hit the dial button. The part of the error that seems concerning is "Failed to save chunk [0, 0]"
Edit: i should have checked first but I see there is ver7.0.7 of rftoolsdim. Will try the latest release and report back. 
Edit 2: updated rftoolsdim ver 7.0.7 now crashes my game when I add another lost knowledge to the knowledge holder and when I right click the dimlet workbench block. Should I open a separate issue track for that? I get the crash in the pastebin link: https://pastebin.com/LXeGAzhR I also still get the invalid destination when dialing my test rftools dim. going to delete the testing1 dim folder and try to regen it with 7.0.7.
Edit 3: deleting the testing1 rftools dim folder in the dimension/rftoolsdim folder and restarting my test world still gets the invalid destination on the dialing device. Not sure what else to try.
Note: edits 2 and 3 are completed without optifine.

When I look at the log, I receive the following error when trying to load any rftools dim:
[05Apr2021 17:55:32.861] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 5
	Listeners:
		0: NORMAL
		1: ASM: net.minecraftforge.common.ForgeInternalHandler@76d257e8 onChunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
		2: ASM: class net.minecraftforge.client.model.ModelDataManager onChunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2987/1750040348@7df236c9
		4: ASM: class com.minecolonies.coremod.event.EventHandler onChunkUnLoad(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$2987/1750040348@6bd1880f
		6: ASM: class com.simibubi.create.events.CommonEvents onChunkUnloaded(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
		7: ASM: class blusunrize.immersiveengineering.api.wires.NetworkSanitizer chunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
		8: ASM: de.ellpeck.naturesaura.events.CommonEvents@68b7fc43 onChunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
		9: ASM: com.simibubi.create.foundation.command.ChunkUtil@5728cf7 chunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
		10: ASM: class mekanism.common.command.ChunkCommand onChunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
java.lang.NullPointerException
	at appeng.hooks.TickHandler.onUnloadChunk(TickHandler.java:180)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.call(Reflector.java:1084)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1357)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1343)
	at net.minecraft.world.server.ChunkManager.lambda$scheduleSave$10(ChunkManager.java:511)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:488)
	at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:460)
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:323)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[05Apr2021 17:55:32.861] [Server thread/ERROR] [net.minecraft.world.server.ChunkManager/]: Failed to save chunk [0, 0]
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:488) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:460) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:323) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at appeng.hooks.TickHandler.onUnloadChunk(TickHandler.java:180) ~[appliedenergistics2:8.3.0-alpha.2]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at net.optifine.reflect.Reflector.call(Reflector.java:1084) ~[?:?]
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1357) ~[?:?]
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1343) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$scheduleSave$10(ChunkManager.java:511) ~[?:?]
	... 13 more

**Comment by Zang518** [comment]
It appears that appliedenergistics2-8.3.0-alpha.2.jar is what was causing the problem for me. I removed all mods except for rftools mod and started loading mods a-c and as soon as I tried, I had encounter the problem. I removed appliedenergistics2-8.3.0-alpha.2.jar, loaded a new world and it was fine. I added the rest of the mods and it's now fine. I forgot I updated that mod due to a ticking entity crash with AE2 8.3.0 alpha.1. Direwolf20s pack at ver1.7.0 isn't using alpha2 yet so I couldn't figure out why the pack wasn't working for me and was for him. appliedenergistics2-8.3.0-alpha.2.jar seems to be the offending mod in my case. 

Did a quick check on the error. Def seems to be AE2 related problem.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5069
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5100

**Comment by McJty** [comment]
Ok, applied energistics is doing something weird with dimensions/teleportation because this isn't the first time this mod has been associated with my mods not working. Best to report to them

**Comment by 7eggert** [comment]
I recently created dimensions while having appliedenergistics2-8.3.1.jar installed. Not that problem, but landscape (basalt blocks) was sometimes generated on the receiver or no platform was generated. TL;DR: Maybe you can try the new AE version.
