### ISSUE TITLE
1.16.5 Command "createdim" fails

### ISSUE THREAD

**Issue by 7eggert** [McJty/RFToolsDimensions#382]
Issue description: The createdim command requires the optional seed parameter to be there but then complains that the command would not support a seed parameter.

(I suspect that nesting the .then in CommandCreateDim.java should not be nested, but I just quickly googled and found https://www.programcreek.com/java-api-examples/?api=net.minecraft.command.CommandSource)

Steps to reproduce: 

# /rftdim create Normal 0

java.lang.IllegalArgumentException: No such argument 'seed' exists on this command
        at com.mojang.brigadier.context.CommandContext.getArgument(CommandContext.java:85) ~[brigadier-1.0.17.jar:?]
        at mcjty.rftoolsdim.commands.CommandCreateDim.run(CommandCreateDim.java:35) ~[rftoolsdim:1.16-7.0.12-beta]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[brigadier-1.0.17.jar:?]
        at net.minecraft.command.Commands.func_197059_a(Commands.java:217) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1119) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_244548_c(ServerPlayNetHandler.java:1102) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1081) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[18Sep2021 19:03:27.381] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] An unexpected error occurred trying to execute that command
[18Sep2021 19:03:27.382] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] No such argument 'seed' exists on this command

------------------------

# /rftdim create Normal

[18Sep2021 19:03:27.382] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] No such argument 'seed' exists on this command
[18Sep2021 19:04:13.555] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Unknown or incomplete command, see below for error
[18Sep2021 19:04:13.555] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] ...ate Normal<--[HERE]

Versions:
* Minecraft: 1.16.5
* Forge: forge-36.2.0
* McJtyLib: mcjtylib-1.16-5.0.22.jar
* RFTools:rftoolsbase-1.16-2.0.11.jar
* RFTools Dimensions: rftoolsdim-1.16-7.0.12-beta.jar (I looked at the .java file, it didn't change vs. 1.16-7.0.14)

**Comment by McJty** [comment]
The seed is not optional. The syntax is:

/rftoolsdim create \<name\> \<descriptor\> \<seed\>

**Comment by 7eggert** [comment]
I did test it with and without the seed. With the seed it complains about having a seed

java.lang.IllegalArgumentException: No such argument 'seed' exists on this command

(see above for the complete stacktrace)

**Comment by 7eggert** [comment]
Ping: `/rftoolsdim create <name> <descriptor> <seed>` does really not work

**Comment by McJty** [comment]
Can you show me the actual command that you used?

**Comment by McJty** [comment]
@7eggert ping?

**Comment by 7eggert** [comment]
The actual command is `/rftdim create Normal 0`, you missed the first headline 8-)

Ping as in "Did you receive my previous message". I was away for some time and got back to see this bug is still closed and not mentioned in the changelogs.

**Comment by McJty** [comment]
I actually fixed the bug yesterday but just like to note that your command is wrong. 'Normal' is not a valid descriptor file. It has to be something like 'normaltest.json'. i.e. it has to refer to a file containing a descriptor for a dimension

**Comment by McJty** [comment]
But yes, the 'seed' thing was wrong

**Comment by 7eggert** [comment]
Obviously I used an outdated manual, it was hard to find decent documentation (presumably because of being in development); it seemed like I'd be supposed to specify a biome descriptor and browsed the source code to find one. I'll shamelessly ask for a pointer to these files then, and maybe to have one for importing minecraft worlds :-)

Thanks for your work BTW.
