### ISSUE TITLE
Dimlet workbench crashing client in 1.18.2

### ISSUE THREAD

**Issue by Zayenus** [McJty/RFToolsDimensions#404]
The dimlet workbench is crashing my client in 1.18.2 singleplayer.

Opening the workbench crashes the client immediately if it's next to a knowledge holder. It can open to the dimlet workbench screen if it's not placed next to one, but crashes the moment I interact with the screen. 

Versions:
* Minecraft: 1.18.2
* Forge: 40.1.41 (tried other versions as early as 40.1.27)
* McJtyLib: 1.18-6.0.15
* RFTools: 1.18-3.0.9
* RFTools Dimensions: 1.18-8.0.6 (8.0.5 tried as well)

***There was a thread about a similar issue but the problem was with ProjectX, which I don't have installed. 

Stacktrace:
	at mcjty.rftoolsdim.modules.dimlets.data.DimletTools.getReadableNameBlock(DimletTools.java:235) ~[rftoolsdim-1.18-8.0.5.jar%23111!/:1.18-8.0.5] {re:classloading}
	at mcjty.rftoolsdim.modules.dimlets.data.DimletTools.getReadableName(DimletTools.java:208) ~[rftoolsdim-1.18-8.0.5.jar%23111!/:1.18-8.0.5] {re:classloading}
	at mcjty.rftoolsdim.modules.workbench.client.GuiWorkbench.dimletMatches(GuiWorkbench.java:233) ~[rftoolsdim-1.18-8.0.5.jar%23111!/:1.18-8.0.5] {re:classloading}
	at mcjty.rftoolsdim.modules.workbench.client.GuiWorkbench.lambda$updateList$0(GuiWorkbench.java:221) ~[rftoolsdim-1.18-8.0.5.jar%23111!/:1.18-8.0.5] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601) ~[?:?] {}
	at mcjty.rftoolsdim.modules.workbench.client.GuiWorkbench.updateList(GuiWorkbench.java:223) ~[rftoolsdim-1.18-8.0.5.jar%23111!/:1.18-8.0.5] {re:classloading}
	at mcjty.rftoolsdim.modules.workbench.client.GuiWorkbench.m_7286_(GuiWorkbench.java:254) ~[rftoolsdim-1.18-8.0.5.jar%23111!/:1.18-8.0.5] {re:classloading}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6305_(AbstractContainerScreen.java:92) ~[client-1.18.2-20220404.173914-srg.jar%23136!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at mcjty.lib.gui.GenericGuiContainer.m_6305_(GenericGuiContainer.java:266) ~[mcjtylib-1.18-6.0.15.jar%2396!/:1.18-6.0.15] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:386) ~[forge-1.18.2-40.1.41-universal.jar%23141!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:379) ~[forge-1.18.2-40.1.41-universal.jar%23141!/:?] {re:mixin,re:classloading}
-- Screen render details --
Details:
	Screen name: mcjty.rftoolsdim.modules.workbench.client.GuiWorkbench
	Mouse location: Scaled: (242, 134). Absolute: (971.000000, 537.000000)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:890) ~[client-1.18.2-20220404.173914-srg.jar%23136!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23136!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23136!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23136!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.41.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by McJty** [comment]
Version 8.0.7 should fix this
