### ISSUE TITLE
Server crash from RFTools Dimensions

### ISSUE THREAD

**Issue by AlbertBence** [McJty/RFToolsDimensions#407]
Issue description: 
The server crash, when some dimension (not all) is chunkloaded. Before the server crash I get very strange message spam in console:
"apple, golden apple"
I get this every tick, when the server is near to crash.

Steps to reproduce: 
I don't know how to reproduce, because we play with a massive custom modpack.

Versions:
* Minecraft: 1.18.1
* Forge: 1.18.1-39.1.0
* McJtyLib: 1.18-6.0.10
* RFTools Base: 1.18-3.0.6
* RFTools Dimensions: 1.18-8.0.3

Possibly incompatible mods: 
SecurityCraft
Advanced Peripherials
AE Infinity Booster
AlexsMobs
AppliedEnergetics2
AutoRegLib
balm
BetterVillage
bigger reactors
Biomes O Plenty
blockui
Botania
cc tweaked
chunkloaders
citadel
cloth-config
create
cocumber
curios
DimStorage
domum_ornamentum
drinkbeer
Enhanced Farming
Extra Disks
Extreme Reactors 2
feature nbt deadblock be gone
flywheel
grapplemod
idas
Immersive Engineering
Iron Jetpacks
jei
Library Ferret
Mantle
Minecolonies
Multi Piston
Mystical Agriculture
no null processors
Patchouli
Phosphophyllite
Quark
quartz
refined pipes
Refined Storage
SereneSeasons
silent gear
silent lib
Simple Backups
Storage Drawers
Structurize
supermartijn542configlib
supermartijn542corelib
Tinkers Construct
Terra Blender
Torchmaster
Trapcraft
Waystones
Zero Core 2

Relevant logs, if any: 
[20:41:22] [Server thread/INFO]: --------------------------------------------------
Attempting to create dimension:
    ATTRIBUTE: nooceans
    ATTRIBUTE: cities
    FLUID: minecraft:water
    TERRAIN: platforms
    STRUCTURE: default
    STRUCTURE: none
    STRUCTURE: none
    BLOCK: tconstruct:white_clear_stained_glass
    FEATURE: spheres
    TAG: minecraft:dirt
    FEATURE: spheres
    BIOME: minecraft:the_end
    BIOME_CONTROLLER: single
    TIME: normal
--------------------------------------------------
[20:41:22] [Server thread/INFO]: --------------------------------------------------
Compiled Descriptor:
    TERRAIN: platforms
    TIME: normal
    SKY: 
    LIQUID: minecraft:water
    BLOCK: minecraft:stone
    ATTR: nooceans
    ATTR: cities
    BIOME CTRL: single
        BIOME: minecraft:the_end
    STRUCTURE: minecraft:default
    STRUCTURE: minecraft:none
    STRUCTURE: minecraft:none
    FEATURE: spheres
        BLOCK: tconstruct:white_clear_stained_glass
        LIQUID: minecraft:water
    FEATURE: spheres
        BLOCK: minecraft:dirt
        BLOCK: minecraft:grass_block
        BLOCK: minecraft:podzol
        BLOCK: minecraft:coarse_dirt
        BLOCK: minecraft:mycelium
        BLOCK: minecraft:rooted_dirt
        BLOCK: minecraft:moss_block
        BLOCK: biomesoplenty:origin_grass_block
        BLOCK: biomesoplenty:glowing_moss_block
        BLOCK: securitycraft:reinforced_grass_block
        BLOCK: securitycraft:reinforced_dirt
        BLOCK: securitycraft:reinforced_coarse_dirt
        BLOCK: securitycraft:reinforced_podzol
        BLOCK: securitycraft:reinforced_moss_block
        BLOCK: securitycraft:reinforced_mycelium
        BLOCK: botania:dry_grass
        BLOCK: botania:golden_grass
        BLOCK: botania:infused_grass
        BLOCK: botania:mutated_grass
        BLOCK: botania:scorched_grass
        BLOCK: botania:vivid_grass
        LIQUID: minecraft:water
--------------------------------------------------
[20:41:22] [Server thread/INFO]: Loading Minecolonies colony manager Backup Data
[20:41:22] [Server thread/INFO]: Backup Load Complete
[20:41:22] [Server thread/ERROR]: Was unable to check if rftoolsdim:rnd3 is using Terraforged's ChunkGenerator.
[20:41:22] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: mcjty/lostcities/api/ILostCities
	at mcjty.rftoolsdim.compat.LostCityCompat.registerDimension(LostCityCompat.java:29) ~[rftoolsdim-1.18-8.0.3.jar%2380!/:1.18-8.0.3]
	at mcjty.rftoolsdim.dimension.terraintypes.RFToolsChunkGenerator.checkForCities(RFToolsChunkGenerator.java:110) ~[rftoolsdim-1.18-8.0.3.jar%2380!/:1.18-8.0.3]
	at mcjty.rftoolsdim.dimension.terraintypes.RFToolsChunkGenerator.m_183621_(RFToolsChunkGenerator.java:117) ~[rftoolsdim-1.18-8.0.3.jar%2380!/:1.18-8.0.3]
	at net.minecraft.world.level.chunk.ChunkStatus.m_156246_(ChunkStatus.java:116) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_183270_(ChunkStatus.java:313) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$20(ChunkMap.java:552) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar%2329!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:550) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:58) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: mcjty.lostcities.api.ILostCities
	at mcjty.rftoolsdim.compat.LostCityCompat.registerDimension(LostCityCompat.java:29) ~[rftoolsdim-1.18-8.0.3.jar%2380!/:1.18-8.0.3]
	at mcjty.rftoolsdim.dimension.terraintypes.RFToolsChunkGenerator.checkForCities(RFToolsChunkGenerator.java:110) ~[rftoolsdim-1.18-8.0.3.jar%2380!/:1.18-8.0.3]
	at mcjty.rftoolsdim.dimension.terraintypes.RFToolsChunkGenerator.m_183621_(RFToolsChunkGenerator.java:117) ~[rftoolsdim-1.18-8.0.3.jar%2380!/:1.18-8.0.3]
	at net.minecraft.world.level.chunk.ChunkStatus.m_156246_(ChunkStatus.java:116) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_183270_(ChunkStatus.java:313) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$20(ChunkMap.java:552) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar%2329!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:550) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:58) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.18.1-20211210.034407-srg.jar%2398!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

**Comment by McJty** [comment]
Those are very old versions. Please update
