### ISSUE TITLE
Entire game broken after crash

### ISSUE THREAD

**Issue by JavaFPS** [McJty/RFToolsDimensions#420]
Issue description: 
Used RFTools Dim in Stoneblock 3 with some friends to go to another world, upon arriving in that world it went smooth for a minute and then all of a sudden it crashed, after restarting, I spawned in an entirely different location, I was no longer in the dimension I was when I crashed and the Porter does not work to get me to my home either. I tried multiple things like restoring backups but even with the backups it just spawns me in the middle of nowhere. I also tried deleting all rftoolsdim dimensions in the folder but that did not help either, issue persists.

Steps to reproduce: 

Make a new RFTools Dimension, go into it.
Crash.
Restart.
Have Error.

Versions:
* Minecraft: 
* Forge: 
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.18-6.0.18
* RFTools: rftoolsbase-1.18-3.0.11
* RFTools Dimensions: rftoolsdim-1.18-8.0.9

Possibly incompatible mods:  Was just playing stoneblock 3 :/

Relevant logs, if any: 
[crash-2022-11-15_01.30.01-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/10008230/crash-2022-11-15_01.30.01-server.txt)

**Comment by McJty** [comment]
It seems to be crashing in REI for some reason. Perhaps also report to them? Is see this in the crashlog:

```
java.lang.IllegalStateException: Accessing PalettedContainer from multiple threads
	at net.minecraft.util.ThreadingDetector.m_199417_(ThreadingDetector.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.minecraft.util.ThreadingDetector.m_199422_(ThreadingDetector.java:69) ~[client-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.minecraft.world.level.chunk.PalettedContainer.m_63120_(PalettedContainer.java:42) ~[client-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunkSection.m_188003_(LevelChunkSection.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkAccess.m_183442_(ChunkAccess.java:390) ~[client-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:B,re:mixin}
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_204586_(NoiseBasedChunkGenerator.java:134) ~[client-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_204595_(NoiseBasedChunkGenerator.java:124) ~[client-1.18.2-20220404.173914-srg.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}

```
