### ISSUE TITLE
Crash that corrupts world data caused by the Researcher.

### ISSUE THREAD

**Issue by OutcastsAnonymous** [McJty/RFToolsDimensions#447]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-04-19 20:43:30
Description: Ticking block entity

java.lang.ClassCastException: class net.minecraft.tags.TagKey cannot be cast to class java.lang.Comparable (net.minecraft.tags.TagKey is in module minecraft@1.19.4 of loader 'TRANSFORMER' @1e236278; java.lang.Comparable is in module java.base of loader 'bootstrap')
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47) ~[?:?] {}
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?] {}
	at java.util.TimSort.sort(TimSort.java:220) ~[?:?] {}
	at java.util.Arrays.sort(Arrays.java:1307) ~[?:?] {}
	at java.util.ArrayList.sort(ArrayList.java:1721) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392) ~[?:?] {}
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:528) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?] {}
	at mcjty.rftoolsdim.modules.knowledge.data.KnowledgeManager.getMostImportantIsTag(KnowledgeManager.java:138) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.knowledge.data.KnowledgeManager.getReasonBiome(KnowledgeManager.java:127) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.knowledge.data.KnowledgeManager.getKnowledgeSetReason(KnowledgeManager.java:109) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.knowledge.data.KnowledgeManager.getKnownPatterns(KnowledgeManager.java:297) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.knowledge.items.LostKnowledgeItem.createRandomLostKnowledge(LostKnowledgeItem.java:108) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.workbench.blocks.ResearcherTileEntity.researchKnowledge(ResearcherTileEntity.java:254) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.workbench.blocks.ResearcherTileEntity.research(ResearcherTileEntity.java:168) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.workbench.blocks.ResearcherTileEntity.tickServer(ResearcherTileEntity.java:154) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.lib.tileentity.TickingTileEntity.tick(TickingTileEntity.java:18) ~[mcjtylib-1.19.4-7.2.4.jar%23178!/:1.19.4-7.2.4] {re:classloading}
	at mcjty.lib.blocks.BaseBlock.runTick(BaseBlock.java:343) ~[mcjtylib-1.19.4-7.2.4.jar%23178!/:1.19.4-7.2.4] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:693) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:786) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:474) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:333) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47) ~[?:?] {}
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?] {}
	at java.util.TimSort.sort(TimSort.java:220) ~[?:?] {}
	at java.util.Arrays.sort(Arrays.java:1307) ~[?:?] {}
	at java.util.ArrayList.sort(ArrayList.java:1721) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392) ~[?:?] {}
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:528) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?] {}
	at mcjty.rftoolsdim.modules.knowledge.data.KnowledgeManager.getMostImportantIsTag(KnowledgeManager.java:138) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.knowledge.data.KnowledgeManager.getReasonBiome(KnowledgeManager.java:127) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.knowledge.data.KnowledgeManager.getKnowledgeSetReason(KnowledgeManager.java:109) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.knowledge.data.KnowledgeManager.getKnownPatterns(KnowledgeManager.java:297) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.knowledge.items.LostKnowledgeItem.createRandomLostKnowledge(LostKnowledgeItem.java:108) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.workbench.blocks.ResearcherTileEntity.researchKnowledge(ResearcherTileEntity.java:254) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.workbench.blocks.ResearcherTileEntity.research(ResearcherTileEntity.java:168) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.rftoolsdim.modules.workbench.blocks.ResearcherTileEntity.tickServer(ResearcherTileEntity.java:154) ~[rftoolsdim-1.19.4-10.1.2.jar%23187!/:1.19.4-10.1.2] {re:classloading}
	at mcjty.lib.tileentity.TickingTileEntity.tick(TickingTileEntity.java:18) ~[mcjtylib-1.19.4-7.2.4.jar%23178!/:1.19.4-7.2.4] {re:classloading}
	at mcjty.lib.blocks.BaseBlock.runTick(BaseBlock.java:343) ~[mcjtylib-1.19.4-7.2.4.jar%23178!/:1.19.4-7.2.4] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:693) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:786) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:474) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:333) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: rftoolsdim:researcher // mcjty.rftoolsdim.modules.workbench.blocks.ResearcherTileEntity
	Block: Block{rftoolsdim:researcher}
	Block location: World: (-55,-18,-26), Section: (at 9,14,6 in -4,-2,-2; chunk contains blocks -64,-64,-32 to -49,319,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Block: Block{rftoolsdim:researcher}
	Block location: World: (-55,-18,-26), Section: (at 9,14,6 in -4,-2,-2; chunk contains blocks -64,-64,-32 to -49,319,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:693) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:786) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:474) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:333) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 20212806 game time, 484865 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 45644 (now: false), thunder time: 29397 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[server-1.19.4-20230314.122934-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Linux (amd64) version 4.19.0-18-amd64
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 744070368 bytes (709 MiB) / 1965031424 bytes (1874 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3800X 8-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 53676.13
	Virtual memory used (MB): 68544.25
	Swap memory total (MB): 21503.99
	Swap memory used (MB): 21103.83
	JVM Flags: 2 total; -Xmx3072M -Xms1024M
	Server Running: true
	Player Count: 0 / 60; []
	Data Packs: vanilla, mod:forge, mod:customizableelytra (incompatible), mod:amplifiednether (incompatible), mod:betterdungeons, mod:enchdesc (incompatible), mod:doubledoors (incompatible), mod:entangled (incompatible), mod:mousetweaks, mod:supermartijn642configlib (incompatible), mod:ping (incompatible), mod:betterwitchhuts, mod:harvestwithease, mod:playeranimator (incompatible), mod:creativecore, mod:jei (incompatible), mod:supermartijn642corelib (incompatible), mod:betteroceanmonuments, mod:dynamiclights (incompatible), mod:waystones (incompatible), mod:taxfreelevels (incompatible), mod:shulkerdropstwo (incompatible), mod:collective (incompatible), mod:clumps (incompatible), mod:camera (incompatible), mod:sit, mod:nullscape, mod:yungsextras, mod:yungsapi, mod:betterstrongholds, mod:bookshelf (incompatible), mod:betterdeserttemples, mod:balm, mod:ears (incompatible), mod:chat_heads (incompatible), mod:betterfortresses, mod:cloth_config (incompatible), mod:voicechat (incompatible), mod:sound_physics_remastered (incompatible), mod:appleskin (incompatible), mod:stackrefill (incompatible), mod:mavapi (incompatible), mod:revampedwolf (incompatible), mod:mavm (incompatible), mod:cosmeticarmorreworked (incompatible), mod:bettermineshafts, mod:emotecraft (incompatible), mod:corpse (incompatible), mod:mcjtylib (incompatible), mod:concreteconversion (incompatible), mod:pipez (incompatible), mod:peacefulrecipes (incompatible), mod:fallingtree, mod:rftoolsbase (incompatible), mod:rftoolsstorage (incompatible), mod:rftoolspower (incompatible), mod:rftoolsdim (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.0.42.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.42.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.0.42.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.0.42.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.42.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		YungsBetterDungeons-1.19.4-Forge-3.4.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.19.4-Forge-3.4.0  |DONE      |Manifest: NOSIGNATURE
		doubledoors-1.19.4-4.5.jar                        |Double Doors                  |doubledoors                   |4.5                 |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.6b-forge-mc1.19.jar  |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6b              |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.19.4-Forge-2.3.0.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.19.4-Forge-2.3.0  |DONE      |Manifest: NOSIGNATURE
		harvestwithease-1.19.4-6.0.1.1-forge.jar          |Harvest with ease             |harvestwithease               |6.0.1.1             |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2+1.19.4.jar       |Player Animator               |playeranimator                |1.0.2+1.19.4        |DONE      |Manifest: NOSIGNATURE
		jei-1.19.4-forge-13.1.0.2.jar                     |Just Enough Items             |jei                           |13.1.0.2            |DONE      |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.19.4-Forge-2.3.0.jar  |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.19.4-Forge-2.3.0  |DONE      |Manifest: NOSIGNATURE
		dynamiclights-1.19.4.1.jar                        |Dynamic Lights                |dynamiclights                 |1.19.4.1            |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.19.4-13.0.1.jar                 |Waystones                     |waystones                     |13.0.1              |DONE      |Manifest: NOSIGNATURE
		TaxFreeLevels-1.3.5-forge-1.19.jar                |Tax Free Levels               |taxfreelevels                 |1.3.5               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.19.4-10.0.0.2.jar                  |Clumps                        |clumps                        |10.0.0.2            |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.19.4-Forge-3.10.1.jar                  |YUNG's API                    |yungsapi                      |1.19.4-Forge-3.10.1 |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.4-18.0.2.jar                 |Bookshelf                     |bookshelf                     |18.0.2              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mcjtylib-1.19.4-7.2.4.jar                         |McJtyLib                      |mcjtylib                      |1.19.4-7.2.4        |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.19-4.1.7.jar                        |RFToolsBase                   |rftoolsbase                   |1.19-4.1.7          |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.19.4-Forge-2.4.0.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.19.4-Forge-2.4.0  |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.19.4-6.0.2.jar                       |Balm                          |balm                          |6.0.2               |DONE      |Manifest: NOSIGNATURE
		chat_heads-0.10.8-forge-1.19.3.jar                |Chat Heads                    |chat_heads                    |0.10.8              |DONE      |Manifest: NOSIGNATURE
		rftoolspower-1.19-5.1.2.jar                       |RFToolsPower                  |rftoolspower                  |1.19-5.1.2          |DONE      |Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.19.4-Forge-1.2.0.jar|YUNG's Better Nether Fortresse|betterfortresses              |1.19.4-Forge-1.2.0  |DONE      |Manifest: NOSIGNATURE
		cloth-config-10.0.96-forge.jar                    |Cloth Config v10 API          |cloth_config                  |10.0.96             |DONE      |Manifest: NOSIGNATURE
		forge-1.19.4-45.0.42-universal.jar                |Forge                         |forge                         |45.0.42             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		stackrefill-1.19.4-4.0.jar                        |Stack Refill                  |stackrefill                   |4.0                 |DONE      |Manifest: NOSIGNATURE
		revampedwolf-1.19.4-4.0.0.jar                     |RevampedWolf                  |revampedwolf                  |1.19.4-4.0.0        |DONE      |Manifest: NOSIGNATURE
		emotecraft-for-MC1.19.4-2.2.7-b.build.48-forge.jar|Emotecraft                    |emotecraft                    |2.2.7-b.build.48    |DONE      |Manifest: NOSIGNATURE
		corpse-1.19.4-1.0.3.jar                           |Corpse                        |corpse                        |1.19.4-1.0.3        |DONE      |Manifest: NOSIGNATURE
		server-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |DONE      |Manifest: NOSIGNATURE
		customizableelytra-1.19.4-1.7.6.jar               |Customizable Elytra           |customizableelytra            |1.19.4-1.7.6        |DONE      |Manifest: NOSIGNATURE
		Amplified_Nether_1.19.4_v1.2.1a.jar               |Amplified Nether              |amplifiednether               |1.2.1a              |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.19.4-2.4.4.jar                  |Simple Voice Chat             |voicechat                     |1.19.4-2.4.4        |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.19.4-1.1.0.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.19.4-1.1.0        |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.19.4-15.0.1.jar   |EnchantmentDescriptions       |enchdesc                      |15.0.1              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		entangled-1.3.13-forge-mc1.19.3.jar               |Entangled                     |entangled                     |1.3.13              |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.19.4-2.24.jar               |Mouse Tweaks                  |mousetweaks                   |2.24                |DONE      |Manifest: NOSIGNATURE
		Ping-1.19.4-1.9.3.jar                             |Ping                          |ping                          |1.19.4-1.9.3        |DONE      |Manifest: NOSIGNATURE
		concreteconversion-1.19.4-6.1.0.2-forge.jar       |Concrete Conversion           |concreteconversion            |1.19.4-6.1.0.2-forge|DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.7_mc1.19.4.jar           |CreativeCore                  |creativecore                  |2.10.7              |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.6-forge-mc1.19.4.jar   |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.6               |DONE      |Manifest: NOSIGNATURE
		pipez-1.19.4-1.0.3.jar                            |Pipez                         |pipez                         |1.19.4-1.0.3        |DONE      |Manifest: NOSIGNATURE
		shulkerdropstwo-1.19.4-3.1.jar                    |Shulker Drops Two             |shulkerdropstwo               |3.1                 |DONE      |Manifest: NOSIGNATURE
		rftoolsstorage-1.19-4.1.2.jar                     |RFToolsStorage                |rftoolsstorage                |1.19-4.1.2          |DONE      |Manifest: NOSIGNATURE
		collective-1.19.4-6.54.jar                        |Collective                    |collective                    |6.54                |DONE      |Manifest: NOSIGNATURE
		camera-1.19.4-1.0.3.jar                           |Camera Mod                    |camera                        |1.19.4-1.0.3        |DONE      |Manifest: NOSIGNATURE
		sit-1.19.4-1.3.3.jar                              |Sit                           |sit                           |1.3.3               |DONE      |Manifest: NOSIGNATURE
		Nullscape_1.19.4_v1.2.1.jar                       |Nullscape                     |nullscape                     |1.2.1               |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.19.4-Forge-3.3.0.jar                |YUNG's Extras                 |yungsextras                   |1.19.4-Forge-3.3.0  |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.19.4-Forge-3.4.0.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.19.4-Forge-3.4.0  |DONE      |Manifest: NOSIGNATURE
		rftoolsdim-1.19.4-10.1.2.jar                      |RFToolsDimensions             |rftoolsdim                    |1.19.4-10.1.2       |DONE      |Manifest: NOSIGNATURE
		PeacefulRecipes-1.9(1).jar                        |Peaceful Recipes              |peacefulrecipes               |1.9                 |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.19.4-2.4.3.jar                |AppleSkin                     |appleskin                     |2.4.3+mc1.19.4      |DONE      |Manifest: NOSIGNATURE
		ears-forge-1.19.4-1.4.6.jar                       |Ears                          |ears                          |1.4.6               |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.19.4-3.12.1.jar                     |FallingTree                   |fallingtree                   |3.12.1              |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		mavapi-1.0.4-mc1.19.4.jar                         |More Axolotl Variants API     |mavapi                        |1.0.4               |DONE      |Manifest: NOSIGNATURE
		mavm-1.2.2-mc1.19.4.jar                           |More Axolotl Variants Mod     |mavm                          |1.2.2               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.19.4-v1.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.19.4-v1           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		YungsBetterMineshafts-1.19.4-Forge-3.4.0.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.19.4-Forge-3.4.0  |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d443cd77-f7ff-428e-b639-3177956320f9
	FML: 45.0
	Forge: net.minecraftforge:45.0.42

This has corrupted two single player worlds, and a server world which I am currently in the process of recovering.

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Should be fixed with 10.1.3
