### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by therodet** [McJty/RFToolsDimensions#78]
Getting java.lang.NullPointerException: Ticking block entity about 1/2 the time when dimension builder reaches 100% creating a new dim.

`java.lang.NullPointerException: Ticking block entity
	at net.minecraft.world.biome.Biome$SpawnListEntry.<init>(Biome.java:640)
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.<init>(GenericChunkGenerator.java:276)
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.func_186060_c(GenericWorldProvider.java:291)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:855)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:115)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18)
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:230)
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:772)
	at mcjty.rftoolsdim.dimensions.RfToolsDimensionManager.touchSpawnChunk(RfToolsDimensionManager.java:409)
	at mcjty.rftoolsdim.dimensions.RfToolsDimensionManager.createNewDimension(RfToolsDimensionManager.java:402)
	at mcjty.rftoolsdim.blocks.builder.DimensionBuilderTileEntity.createDimensionTick(DimensionBuilderTileEntity.java:212)
	at mcjty.rftoolsdim.blocks.builder.DimensionBuilderTileEntity.checkStateServer(DimensionBuilderTileEntity.java:115)
	at mcjty.rftoolsdim.blocks.builder.DimensionBuilderTileEntity.func_73660_a(DimensionBuilderTileEntity.java:97)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)`

**Comment by McJty** [comment]
Please more info. What version of MC? What version of RFTools Dimensions? What kind of dimension are you making?

**Comment by therodet** [comment]
Sorry; I should know better than that...
MC 1.10.2
RFTools 5.82
RFTools Dim 4.53
Forge 12.18.3.2221
Only using two digit dimlets, all else auto-selected. Default configs.

**Comment by josephcsible** [comment]
I think this is fixed as of 5.50. Can you confirm?
