### ISSUE TITLE
Can't join server [MC 1.10.2] [RFToolsDim 1.1x-4.54] [Forge 2221]

### ISSUE THREAD

**Issue by InjuredWolf** [McJty/RFToolsDimensions#82]
I get this output in my client console when I try to join a world:

[20:03:14] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at mcjty.rftoolsdim.dimensions.DimensionStorage.getDimensionStorage(DimensionStorage.java:40) ~[DimensionStorage.class:?]
	at mcjty.rftoolsdim.network.ReturnEnergyHelper.setEnergyLevel(ReturnEnergyHelper.java:14) ~[ReturnEnergyHelper.class:?]
	at mcjty.rftoolsdim.network.PacketReturnEnergy$Handler.lambda$onMessage$0(PacketReturnEnergy.java:44) ~[PacketReturnEnergy$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 9 more

**Comment by McJty** [comment]
Do you have sponge? Did you update that recently? Sponge was recently fixed for bugs in combination with rftools dimensions

**Comment by InjuredWolf** [comment]
I don't use Sponge, no.

**Comment by McJty** [comment]
Can you give me a full log?

**Comment by InjuredWolf** [comment]
From client launch? It's not a crash, if that helps. just comes up with 'A fatal error has occurred, this connection is terminated'

**Comment by McJty** [comment]
That's a crash too and I need the log for more info

**Comment by InjuredWolf** [comment]
This is what it is from when I enter the multiplayer screen:

http://pastebin.com/5S4ExzJG

**Comment by McJty** [comment]
Can you describe to me how you got to this point? What kind of dimension did you last make? Is that the dimension you're in? All info you can give me

**Comment by InjuredWolf** [comment]
I had just created the world on the server using Botania's Garden of Glass mode. Then I booted up my client and tried to join it. Would the GoG part have an issue?

**Comment by McJty** [comment]
I have no clue what that does... So you haven't tried to make any rftools dimensions? Very strange. But I see tons of other errors in your log not related to rftools dimensions. I wonder if you pack isn't corrupt or something.

**Comment by InjuredWolf** [comment]
Garden of Glass makes the world a skyblock.

Maybe... I'll try running it without GoG...
A single player world works fine. I'll compare my server and client settings...
